### ISSUE TITLE
egg-links in site-packages point to invalid path at run-time

### ISSUE THREAD

**Issue by punkadiddle** [cloudfoundry/python-buildpack#102]
## What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.106.0",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "routing_endpoint": "https://api.run.pivotal.io/routing"
}
cf version 6.35.2+88a03e995.2018-03-15

## What version of the buildpack you are using?
1.6.11

## If you were attempting to accomplish a task, what was it you were attempting to do?

Run a Pastedeploy/Flask/Gunicorn App:
`web: gunicorn --paste development.ini --bind :$PORT`

The ini-file refers to my package:
```
[app:main]
use = egg:demo_api
```

Dependencies are provided through setup.cfg and requirements.txt.

From the log, the demo_app package gets installed during build "Running setup.py develop for demo-api".

## What did you expect to happen?

For Gunicorn/Paste to find my egg and run my application (as is the case in the current PCF Dev 1.11).

## What was the actual behavior?

Log: `2018-03-31T22:35:58.645+02:00 [APP/PROC/WEB/0] [ERR] pkg_resources.DistributionNotFound: The 'demo_api' distribution was not found and is required by the application`

The egg is defect. Since it is installed as a development package, a link is placed in the site-packages folder. During build the ENVIRONMENT differs from the ENVIRONMENT during runtime.

I created a minimal Flask App and visited the running container.

```bash
# What had been installed
cd ~/deps/0/lib/python3.6/site-packages
cat demo-api.egg-link
/tmp/app/src
# ^ this directory does not exist anymore

# Reinstalling with the environment setup identically as for the running gunicorn with minimal app setup.
cd ~/app
pip install -e .

# Now the installation looks and works as expected
cd ~/deps/0/lib/python3.6/site-packages
cat demo-api.egg-link
/home/vcap/app/src
# ^ this directory is valid during run

# now my original app can be started (on a different port)
```

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by punkadiddle** [comment]
Patched it for now using a post_compile script:
```find -L "$PYTHONPATH/lib" -type f -iregex '.*/site-packages/.*egg-link$' -print0 | xargs -0 --verbose -I{} sh -c 'echo "/home/vcap/app/src" > "$1"' -- {}```

**Comment by sclevine** [comment]
Thanks @punkadiddle,

In CF, apps are launched from a different directory than the directory they are built in.

We will look into ways we could configure pip to generate egg links without the build path.

**Comment by dfreilich** [comment]
@punkadiddle This issue should be fixed when we fully transition to the the python [cloud native buildpacks](https://buildpacks.io/), where the app directory will stay the same between staging and launch. I'll close it for now.
