### ISSUE TITLE
 PIP Install failing with error ~ Could not find a version that satisfies the requirement Flask<1

### ISSUE THREAD

**Issue by egmanoharan** [cloudfoundry/python-buildpack#109]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version 6.32.0+0191c33d9.2017-09-26

What version of the buildpack you are using?

python_buildpack-cached-v1.6.11.zip

If you were attempting to accomplish a task, what was it you were attempting to do?

While trying to deploy a python app, getting an error  "PIP Install failing with error ~ Could not find a version that satisfies the requirement Flask<1"

What did you expect to happen?

The app should deploy

What was the actual behavior?

Failing with an error "PIP Install failing with error ~ Could not find a version that satisfies the requirement Flask<1"

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @egmanoharan,

Could you provide a sample app that reproduces this failure with the latest version of the buildpack?

**Comment by egmanoharan** [comment]
[cf-sample-python-flask.zip](https://github.com/cloudfoundry/python-buildpack/files/2071888/cf-sample-python-flask.zip)

**Comment by egmanoharan** [comment]
I have uploaded the sample app [cf-sample-python-flask.zip]  to reproduce this issue.

**Comment by jfeeny** [comment]
This app works fine for us with python-buildpack `v1.6.11`. 

```
Creating app cf-sample-python-flask111...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 217.57 KiB / 217.57 KiB [==============================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell 0a5d21d6-118b-4591-9e61-59c58434b0ab creating container for instance 89876af5-760f-4b77-8ba4-c0771dd1767d
   Cell 0a5d21d6-118b-4591-9e61-59c58434b0ab successfully created container for instance 89876af5-760f-4b77-8ba4-c0771dd1767d
   Downloading app package...
   Downloaded app package (435.5K)
   -----> Download go 1.9.1
   -----> Running go build supply
   -----> Python Buildpack version 1.6.11
   -----> Supplying Python
   -----> Installing python 2.7.14
          Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.14-linux-x64-30d9c08f.tgz]
   -----> Installing setuptools 38.5.2
          Download [https://buildpacks.cloudfoundry.org/dependencies/setuptools/setuptools-38.5.2-8246123e.zip]
   -----> Installing pip 9.0.1
          Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip/pip-9.0.1-35f01da3.tar.gz]
   -----> Installing pip-pop 0.1.1
          Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Installing pipenv 11.1.4
          Download [https://buildpacks.cloudfoundry.org/dependencies/pipenv/pipenv-v11.1.4-7394418e.tgz]
   -----> Running Pip Install
          Collecting Flask<1 (from -r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/2e/48/f1936dadac2326b3d73f2fe0a964a87d16be16eb9d7fc56f09c1bea3d17c/Flask-0.12.4-py2.py3-none-any.whl (81kB)
          Collecting Jinja2>=2.4 (from Flask<1->-r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
          Collecting Werkzeug>=0.7 (from Flask<1->-r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl (322kB)
          Collecting click>=2.0 (from Flask<1->-r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/34/c1/8806f99713ddb993c5366c362b2f908f18269f8d792aff1abfd700775a77/click-6.7-py2.py3-none-any.whl (71kB)
          Collecting itsdangerous>=0.21 (from Flask<1->-r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/dc/b4/a60bcdba945c00f6d608d8975131ab3f25b22f2bcfe1dab221165194b2d4/itsdangerous-0.24.tar.gz (46kB)
          Collecting MarkupSafe>=0.23 (from Jinja2>=2.4->Flask<1->-r /tmp/contents895704149/deps/0/requirements.txt (line 1))
            Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
          Installing collected packages: MarkupSafe, Jinja2, Werkzeug, click, itsdangerous, Flask
            Running setup.py install for MarkupSafe: started
              Running setup.py install for MarkupSafe: finished with status 'done'
            Running setup.py install for itsdangerous: started
              Running setup.py install for itsdangerous: finished with status 'done'
          Successfully installed Flask-0.12.4 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 click-6.7 itsdangerous-0.24
          You are using pip version 9.0.1, however version 10.0.1 is available.
          You should consider upgrading via the 'pip install --upgrade pip' command.
   -----> Running go build finalize
   Exit status 0
   Uploading droplet, build artifacts cache...
   Uploading build artifacts cache...
   Uploading droplet...
   Uploaded build artifacts cache (37.7M)

Waiting for app to start...

name:              cf-sample-python-flask111
requested state:   started
instances:         1/1
usage:             256M x 1 instances
routes:            cf-sample-python-flask111.v3.pcfdev.io
last uploaded:     Thu 07 Jun 01:47:53 EDT 2018
stack:             cflinuxfs2
buildpack:         https://github.com/cloudfoundry/python-buildpack.git#v1.6.11
start command:     python runserver.py

     state     since                  cpu    memory      disk      details
#0   running   2018-06-07T05:48:46Z   0.0%   0 of 256M   0 of 1G
```

**Comment by 1kaushik1** [comment]
@egmanoharan @jfeeny were you guys able to fix the issue ?,
We are running into a similar issue .

Pasted the error logs while pushing the application

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloaded python_buildpack
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (1.4K)
   -------> Buildpack version 1.5.26
    !     Warning: Your application is missing a Procfile. This file tells Cloud Foundry how to run your application.
    !     Learn more: https://docs.cloudfoundry.org/buildpacks/prod-server.html#procfile
   -----> Installing python-2.7.14
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.14-linux-x64-970d20be.tgz]
   -----> Installing Setuptools (32.1.0)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/setuptools/setuptools-32.1.0-44054eaa.tar.gz]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip/pip-9.0.1-35f01da3.tar.gz]
   -----> Installing Pip (9.0.1)
   -----> Installing pip-pop (0.1.1)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Installing pipenv (4.0.1)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pipenv/pipenv-4.0.1-148f753f.tar.gz]
        $ pip install -r requirements.txt
          Collecting Flask (from -r requirements.txt (line 1))
            **Could not fetch URL https://pypi.python.org/simple/flask/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) - skipping
   No matching distribution found for Flask (from -r requirements.txt (line 1))**
Error staging application: App staging failed in the buildpack compile phase
FAILED
