### ISSUE TITLE
bin/package gone

### ISSUE THREAD

**Issue by jameskhedley** [cloudfoundry/python-buildpack#11]
Hi,

Looks like this was removed by  c8919ddf65 but is still mentioned by Readme.md.

Is it possible to build an offline buildpack without this script? If so, how to do it?

Any help or advice appreciated!

Regards,
James

**Comment by jchesterpivotal** [comment]
Hi @jameskhedley, you're right. We updated the packaging mechanism late last year but we overlooked the readme. 

We have identical reports for [nodejs](https://github.com/cloudfoundry/nodejs-buildpack/issues/12) and [ruby](https://github.com/cloudfoundry/ruby-buildpack/issues/29);  updating the documentation should start today or tomorrow.

When we're done I'll loop back and close this issue. Sorry for the confusion :|

**Comment by jameskhedley** [comment]
No problem, thanks for quick answer!

**Comment by jchesterpivotal** [comment]
We've updated the README, so I am going to close this issue.
