### ISSUE TITLE
source of python-buildpack 1.6.11 dependencies

### ISSUE THREAD

**Issue by luisapace** [cloudfoundry/python-buildpack#116]
Hi, my team would like to use python-buildpack 1.6.11 and to approve that I've to analyze it's source code and the code of its dependencies chain, so be sure that they don't have problematic licenses.

But we were not able to discover the download location of some dependencies packages:

libmemcache 1.0.18	
miniconda2 4.4.10	
miniconda3 4.4.10

Could you please indicate me what they are and at which URL I can download their source code from?

Thanks a lot.

**Comment by sclevine** [comment]
The binary builder contains recipes for each dependency in manifest.yml: https://github.com/cloudfoundry/binary-builder/tree/master/recipe

Note that not all dependencies are open source (though I believe those three are).

**Comment by luisapace** [comment]
Hi, could you please indicate what are the dependencies that are NOT open source and where in the buildpack are they referenced?

**Comment by astrieanna** [comment]
@luisapace There do not appear to be non-opensource dependencies for this buildpack. They would be listed in the `manifest.yml` file, but everything listed there is open-source.

**Comment by mlicursi** [comment]
About libmemcache 1.0.18 I would  add details to  the question from Luisa.

It looks like that the tgz referenced:
https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/python/libmemcache-1.0.18-linux-x64-6d33aa02.tgz  
contains headers and library binaries with a copyright:
 *  Copyright (C) 2011 Data Differential, http://datadifferential.com/

Is this open source code or not? If yes could you point to the source for those binaries? 
If not how it is licensed?

Thanks

**Comment by astrieanna** [comment]
The libffi and libmemcached binaries appear to have been built and added to the buildpack in December 2016. They were build manually (not by a pipeline).

There are comments in our tracker recording the commands used to build them.
Libmemcached: https://www.pivotaltracker.com/story/show/134514831/comments/156234621
(so the source archive was downloaded from https://launchpad.net/libmemcached/1.0/1.0.18/ )

Libffi: https://www.pivotaltracker.com/story/show/134514831/comments/156234599
(so the archive was downloaded from https://sourceware.org/pub/libffi/)

Both of these libraries are open-source.

**Comment by jfeeny** [comment]
@mlicursi @luisapace We'll go ahead and close this issue now, but feel free to re-open if necessary.
