### ISSUE TITLE
NLTK corpus does not work with Pyhton 3 only with Pyhton 2 from buildpack

### ISSUE THREAD

**Issue by cbernecker** [cloudfoundry/python-buildpack#117]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

- For the deployment of our applications we using Travis from IBM Whitewater. So I don't know if this information is relevant for you? 

What version of the buildpack you are using?

- v1.6.21

If you were attempting to accomplish a task, what was it you were attempting to do?

In the runtime.txt I set my Python to version 3.6.5.  I'm using NLTK packages and a corpus of NLTK in my application. In detail we use the corpus "Punkt". The point is that I got with version 3.6.5 the following issue:

_/tmp/app/.cloudfoundry/0/python/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour warn(RuntimeWarning(msg))_

**Travis Stack:**

```
 -----> Downloading NLTK packages: punkt

          /tmp/app/.cloudfoundry/0/python/lib/python3.6/runpy.py:125: RuntimeWarning: 'nltk.downloader' found in sys.modules after import of package 'nltk', but prior to execution of 'nltk.downloader'; this may result in unpredictable behaviour

            warn(RuntimeWarning(msg))

          [nltk_data] Downloading package punkt to

          [nltk_data]     /tmp/app/.cloudfoundry/0/python/nltk_data...

          [nltk_data]   Unzipping tokenizers/punkt.zip.

   -----> Running go build finalize

            Using cached https://files.pythonhosted.org/packages/0f/00/b22a64d36c84e60407da8a7646abd5fa82f13d574bbedfa8f8bd2730f492/cf_deployment_tracker-1.0.4-py2.py3-none-any.whl

            Using cached https://files.pythonhosted.org/packages/9a/42/9c4359e738cd6018829e8779962eb78e24323239e028d6c190507125a65b/cloudant-2.4.0.tar.gz

          Collecting cloudant==2.4.0 (from -r /tmp/app/.cloudfoundry/0/requirements.txt (line 3))

          Collecting numpy==1.14.0 (from -r /tmp/app/.cloudfoundry/0/requirements.txt (line 4))

            Using cached https://files.pythonhosted.org/packages/dc/ac/5c270dffb864f23315e9c1f9e0a0b300c797b3c170666c031c4de42aacae/numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl

          Collecting scipy==1.0.0 (from -r /tmp/app/.cloudfoundry/0/requirements.txt (line 5))

   Failed to compress build artifacts: signal: broken pipe

   Exit status 1

   Staging failed: Exited with status 1
```

When I use the default Python version 2.7.15 from the buildpack it works fine and I don't see any error message. The point is that we working on Python 3 instead of Python 2 on our local machines. For any reason the code works with 2.7.15. But I assume that we will run in an issue sooner or later. So our goal is to have the same version on our Cloud App that we use on our local systems. 

**Steps to reproduce:**

- define in your runtime.txt the python version
- create a requirements.txt and add nltk as a package
- define in your travis.yml
```
python:
  - "3.6"
install:
  - pip install -r requirements.txt
```
- deploy it

What did you expect to happen?

The point is that Travis log section shows no issue when it tries to install all requirements. But in the section "Preparing deploy" when cf counts in and starts to install and download the packages again.  

**Expectation:** The NLTK corpus has to be download able even with Python 3

What was the actual behavior?

- We use Python 2.7.15 as a workaround. 

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
The warnings are not related to the failure. The message:
```
   Failed to compress build artifacts: signal: broken pipe
```
indicates that you ran out of disk space during staging (perhaps due to the NLTK corpora size?).

You didn't provide any info about the foundation you're pushing to. Can you raise the staging disk limit on that foundation?

**Comment by cbernecker** [comment]
@sclevine I don't believe that this is the problem because when I use Pyhton 2.7.15 everything works perfect and why should the size of the corpus be different in Python 3? 

Here are the settings of our foundation - 2GB is the limit! 

```
---
applications:
 - name: XXXXXXXXXX
   random-route: true
   memory: 2048M
   instances: 4
   disk_quota: 2048M
   buildpack: https://github.com/cloudfoundry/python-buildpack
   timeout: 180
   env:
    LOGGING: False
    ELIZA_ENV: dev
```

**Comment by sclevine** [comment]
The staging disk quota is a BOSH (platform) property that can't be adjusted via manifest.yml.

I'm not sure why the droplet is larger for Python 3, but that error is a platform error that only occurs when the droplet can't be constructed (after staging completes successfully).

Could you provide us with a sample that fails on PWS? That might help us identify why the droplet is larger.

**Comment by cbernecker** [comment]
@sclevine sure I'll bundle a demo application on Monday and share a box link with you. But can you tell me what PWS means?
