### ISSUE TITLE
Instructions for `Vendoring App Dependencies` seem incorrect

### ISSUE THREAD

**Issue by dmikusa-pivotal** [cloudfoundry/python-buildpack#12]
The instructions [here](https://github.com/cloudfoundry/python-buildpack#vendoring-app-dependencies) result in an error from pip.

[These instructions](https://groups.google.com/a/cloudfoundry.org/d/msg/vcap-dev/0zVZCZ4tItg/7SdR07PtF5YJ) seem to work.

**Comment by Dannyzen** [comment]
We updated docs in https://github.com/cloudfoundry/python-buildpack/commit/2c3cbeac2a60cf063b7d14a519e0e0710a6a41a7 to cover this.
