### ISSUE TITLE
Request: Please add Requests library to the python buildpack

### ISSUE THREAD

**Issue by jmcclenny-epoc** [cloudfoundry/python-buildpack#120]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?
python_buildpack-cached-cflinuxfs2-v1.6.18.zip

If you were attempting to accomplish a task, what was it you were attempting to do?
Import Requests module for python built applications

What did you expect to happen?
The Requests module is loaded from the buildpack and the application successfully pushes.

What was the actual behavior?
The application failed to deployed because the buildpack does not contain the Requests module.

Purpose:
Requests allows you to send organic, grass-fed HTTP/1.1 requests, without the need for manual labor. There’s no need to manually add query strings to your URLs, or to form-encode your POST data. Keep-alive and HTTP connection pooling are 100% automatic, thanks to urllib3.

Link to module: http://docs.python-requests.org/en/master/

With Response module part of the python buildpack, there is no need to maintain custom buildpacks or docker images to push applications that use the Requests library.

**Comment by sclevine** [comment]
Can you use `requirements.txt` to have the buildpack install this package using pip? Is Requests different from other Python packages somehow?

**Comment by sclevine** [comment]
`pip` will reach out to the internet for dependencies in `requirements.txt` by default, but you can vendor your app before pushing to make this work in disconnected environments.
See: https://docs.cloudfoundry.org/buildpacks/python/index.html#vendoring

We use the same process for ruby gems, node.js modules, etc.

**Comment by jmcclenny-epoc** [comment]
I believe it's working now. Thanks for the help!
