### ISSUE TITLE
Python 3.7.0 not found in latest buildpack version even though mentioned in release notes

### ISSUE THREAD

**Issue by richil-bhalerao** [cloudfoundry/python-buildpack#121]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
=>
`cf curl /v2/info && cf version
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "Cloud Foundry v252",
   "authorization_endpoint": "",
   "token_endpoint": "",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.74.0",
   "app_ssh_endpoint": "",
   "app_ssh_host_key_fingerprint": "a6:d1:08:0b:b0:cb:9b:5f:c4:ba:44:2a:97:26:19:8a",
   "app_ssh_oauth_client": "ssh-proxy",
   "logging_endpoint": "",
   "doppler_logging_endpoint": "",
   "user": "4a5434c6-1835-45cc-9308-44a815f4a88a"
}
cf version 6.29.1+d5129d651.2017-08-17`

What version of the buildpack you are using?
=> v1.6.21

If you were attempting to accomplish a task, what was it you were attempting to do?
=> deploy a python application

What did you expect to happen?
=> Running application on CF

What was the actual behavior?
=> App failed to deploy

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [] I have included steps for reproduction

Logs:
`...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (54.8K)
Staging...
-----> Download go 1.9.1
-----> Running go build supply
-----> Python Buildpack version 1.6.21
-----> Supplying Python
       **ERROR** Could not install python: no match found for 3.7.0 in [2.7.14 2.7.15 3.4.8 3.4.9 3.5.5 3.5.6 3.6.5 3.6.6]
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed`

**Comment by sclevine** [comment]
It looks like 3.7.0 was added for cflinuxfs3 but not for cflinuxfs2. Prioritizing this issue to investigate.

**Comment by sclevine** [comment]
It looks like Python 3.7 does not compile on cflinuxfs2 (based on Ubuntu Trusty), so we'll only be able to provide this dependency for cflinuxfs3 (based on Ubuntu Bionic).
