### ISSUE TITLE
App staging failed in the buildpack compile phase

### ISSUE THREAD

**Issue by jmcclenny-epoc** [cloudfoundry/python-buildpack#122]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.37.0+a40009753.2018-05-25

What version of the buildpack you are using?
python_buildpack-cached-cflinuxfs2-v1.6.21.zip

If you were attempting to accomplish a task, what was it you were attempting to do?
Push an app with vendored dependencies.

What did you expect to happen?
All dependencies would install and the app pushes. The application seems to be failing because of the cffi module.

What was the actual behavior?
See below for logs.

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloaded python_buildpack
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee creating container for instance 6746b066-7713-437d-9292-2473d178f041
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee successfully created container for instance 6746b066-7713-437d-9292-2473d178f041
   Downloading app package...
   Downloading build artifacts cache...
   Downloaded app package (13M)
   Downloaded build artifacts cache (52.7M)
   -----> Python Buildpack version 1.6.21
   -----> Supplying Python
   -----> Installing python 3.6.6
          Copy [/tmp/cache/final/dependencies/56436b1b2610ea56a46975ed6a4938deb0a45022c27fe0c2fa42ad21a121313b/python-3.6.6-linux-x64-cflinuxfs2-429ba7c4.tgz]
   -----> Installing setuptools 40.2.0
          Copy [/tmp/cache/final/dependencies/98828eead5adb1f54717ff5370ac48face2ca8dddb6883d0c05ce9c20c787760/setuptools-40.2.0-47881d54.zip]
   -----> Installing pip 9.0.3
          Copy [/tmp/cache/final/dependencies/c3a7e82c85b3da3338eb252ef6beba4aab71ca639fb5ef3f72ba1daa25f26235/pip-9.0.3-7bf48f9a.tar.gz]
   -----> Installing pip-pop 0.1.1
          Copy [/tmp/cache/final/dependencies/e7f3df1a49d628e69b68a5705ca720d0ecc39e3830867e7128007e03843d921a/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Running Pip Install
          Collecting Flask>=0.12 (from -r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting pymysql (from -r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting requests (from -r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting oauthlib (from -r /tmp/contents528065674/deps/0/requirements.txt (line 5))
          Collecting requests-oauthlib (from -r /tmp/contents528065674/deps/0/requirements.txt (line 6))
          Collecting flask-wtf (from -r /tmp/contents528065674/deps/0/requirements.txt (line 7))
          Collecting flask-sqlalchemy (from -r /tmp/contents528065674/deps/0/requirements.txt (line 8))
          Collecting flask-marshmallow (from -r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting marshmallow-sqlalchemy (from -r /tmp/contents528065674/deps/0/requirements.txt (line 11))
          Collecting Werkzeug>=0.14 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting Jinja2>=2.10 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting itsdangerous>=0.24 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting click>=5.1 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting cryptography (from pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting chardet<3.1.0,>=3.0.2 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting idna<2.8,>=2.5 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting urllib3<1.25,>=1.21.1 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting certifi>=2017.4.17 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting WTForms (from flask-wtf->-r /tmp/contents528065674/deps/0/requirements.txt (line 7))
          Collecting SQLAlchemy>=0.8.0 (from flask-sqlalchemy->-r /tmp/contents528065674/deps/0/requirements.txt (line 8))
          Collecting marshmallow>=2.0.0 (from flask-marshmallow->-r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting six>=1.9.0 (from flask-marshmallow->-r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting asn1crypto>=0.21.0 (from cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting cffi!=1.11.3,>=1.7 (from cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, Flask, idna, asn1crypto, six, pycparser, cffi, cryptography, pymysql, chardet, urllib3, certifi, requests, oauthlib, requests-oauthlib, WTForms, flask-wtf, SQLAlchemy, flask-sqlalchemy, marshmallow, flask-marshmallow, marshmallow-sqlalchemy
            Running setup.py install for Werkzeug: started
              Running setup.py install for Werkzeug: finished with status 'done'
            Running setup.py install for MarkupSafe: started
              Running setup.py install for MarkupSafe: finished with status 'done'
            Running setup.py install for Jinja2: started
              Running setup.py install for Jinja2: finished with status 'done'
            Running setup.py install for itsdangerous: started
              Running setup.py install for itsdangerous: finished with status 'done'
            Running setup.py install for click: started
              Running setup.py install for click: finished with status 'done'
            Running setup.py install for Flask: started
              Running setup.py install for Flask: finished with status 'done'
            Running setup.py install for idna: started
              Running setup.py install for idna: finished with status 'done'
            Running setup.py install for asn1crypto: started
              Running setup.py install for asn1crypto: finished with status 'done'
            Running setup.py install for six: started
              Running setup.py install for six: finished with status 'done'
            Running setup.py install for pycparser: started
              Running setup.py install for pycparser: finished with status 'done'
            Running setup.py install for cffi: started
              Running setup.py install for cffi: finished with status 'error'
              Complete output from command /tmp/contents528065674/deps/0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oequpsav/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1jaodvpk-record/install-record.txt --single-version-externally-managed --compile:
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              running install
              running build
              running build_py
              creating build
              creating build/lib.linux-x86_64-3.6
              creating build/lib.linux-x86_64-3.6/cffi
              copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/model.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/commontypes.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/error.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/cparser.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/api.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/lock.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/__init__.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/verifier.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/recompiler.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_embedding.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.6/cffi
              running build_ext
              building '_cffi_backend' extension
              creating build/temp.linux-x86_64-3.6
              creating build/temp.linux-x86_64-3.6/c
              gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/tmp/contents528065674/deps/0/python/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.6/c/_cffi_backend.o
              c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
               #include <ffi.h>
                               ^
              compilation terminated.
              error: command 'gcc' failed with exit status 1
              
              ----------------------------------------
          Command "/tmp/contents528065674/deps/0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-oequpsav/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-1jaodvpk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-oequpsav/cffi/
          Running pip install without indexes failed. Not all dependencies were vendored. Trying again with indexes.
          Collecting Flask>=0.12 (from -r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting pymysql (from -r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting requests (from -r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting oauthlib (from -r /tmp/contents528065674/deps/0/requirements.txt (line 5))
          Collecting requests-oauthlib (from -r /tmp/contents528065674/deps/0/requirements.txt (line 6))
          Collecting flask-wtf (from -r /tmp/contents528065674/deps/0/requirements.txt (line 7))
          Collecting flask-sqlalchemy (from -r /tmp/contents528065674/deps/0/requirements.txt (line 8))
          Collecting flask-marshmallow (from -r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting marshmallow-sqlalchemy (from -r /tmp/contents528065674/deps/0/requirements.txt (line 11))
          Collecting Werkzeug>=0.14 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting Jinja2>=2.10 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting itsdangerous>=0.24 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting click>=5.1 (from Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting cryptography (from pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting chardet<3.1.0,>=3.0.2 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting idna<2.8,>=2.5 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting urllib3<1.25,>=1.21.1 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting certifi>=2017.4.17 (from requests->-r /tmp/contents528065674/deps/0/requirements.txt (line 4))
          Collecting WTForms (from flask-wtf->-r /tmp/contents528065674/deps/0/requirements.txt (line 7))
          Collecting SQLAlchemy>=0.8.0 (from flask-sqlalchemy->-r /tmp/contents528065674/deps/0/requirements.txt (line 8))
          Collecting marshmallow>=2.0.0 (from flask-marshmallow->-r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting six>=1.9.0 (from flask-marshmallow->-r /tmp/contents528065674/deps/0/requirements.txt (line 10))
          Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->-r /tmp/contents528065674/deps/0/requirements.txt (line 2))
          Collecting asn1crypto>=0.21.0 (from cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting cffi!=1.11.3,>=1.7 (from cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Collecting pycparser (from cffi!=1.11.3,>=1.7->cryptography->pymysql->-r /tmp/contents528065674/deps/0/requirements.txt (line 3))
          Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, click, Flask, idna, asn1crypto, six, pycparser, cffi, cryptography, pymysql, chardet, urllib3, certifi, requests, oauthlib, requests-oauthlib, WTForms, flask-wtf, SQLAlchemy, flask-sqlalchemy, marshmallow, flask-marshmallow, marshmallow-sqlalchemy
            Running setup.py install for Werkzeug: started
              Running setup.py install for Werkzeug: finished with status 'done'
            Running setup.py install for MarkupSafe: started
              Running setup.py install for MarkupSafe: finished with status 'done'
            Running setup.py install for Jinja2: started
              Running setup.py install for Jinja2: finished with status 'done'
            Running setup.py install for itsdangerous: started
              Running setup.py install for itsdangerous: finished with status 'done'
            Running setup.py install for click: started
              Running setup.py install for click: finished with status 'done'
            Running setup.py install for Flask: started
              Running setup.py install for Flask: finished with status 'done'
            Running setup.py install for idna: started
              Running setup.py install for idna: finished with status 'done'
            Running setup.py install for asn1crypto: started
              Running setup.py install for asn1crypto: finished with status 'done'
            Running setup.py install for six: started
              Running setup.py install for six: finished with status 'done'
            Running setup.py install for pycparser: started
              Running setup.py install for pycparser: finished with status 'done'
            Running setup.py install for cffi: started
              Running setup.py install for cffi: finished with status 'error'
              Complete output from command /tmp/contents528065674/deps/0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-302hrel2/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-g4eb9tb_-record/install-record.txt --single-version-externally-managed --compile:
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              Package libffi was not found in the pkg-config search path.
              Perhaps you should add the directory containing `libffi.pc'
              to the PKG_CONFIG_PATH environment variable
              No package 'libffi' found
              running install
              running build
              running build_py
              creating build
              creating build/lib.linux-x86_64-3.6
              creating build/lib.linux-x86_64-3.6/cffi
              copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/model.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/commontypes.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/error.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/cparser.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/api.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/lock.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/__init__.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/verifier.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/recompiler.py -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_embedding.h -> build/lib.linux-x86_64-3.6/cffi
              copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.6/cffi
              running build_ext
              building '_cffi_backend' extension
              creating build/temp.linux-x86_64-3.6
              creating build/temp.linux-x86_64-3.6/c
              gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/tmp/contents528065674/deps/0/python/include/python3.6m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.6/c/_cffi_backend.o
              c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
               #include <ffi.h>
                               ^
              compilation terminated.
              error: command 'gcc' failed with exit status 1
              
              ----------------------------------------
          Command "/tmp/contents528065674/deps/0/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-302hrel2/cffi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-g4eb9tb_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-302hrel2/cffi/
          Running pip install failed. You need to include all dependencies in the vendor directory.
          **ERROR** Could not install pip packages: Couldn't run pip: exit status 1
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Thanks for the report! Can you provide a sample app that fails to push with this error?

**Comment by jmcclenny-epoc** [comment]
I will work on one and make it available as soon as possible!

**Comment by jmcclenny-epoc** [comment]
Here's a sample app:
https://github.com/jmcclenny-epoc/cf-python-sample-app

Ran into an interesting issue when I tried to push the app (forgot to define the python runtime), I got the following error defined below.

Now I'm wondering if running Python 3.7 as a venv is causing the issue and using python 3.6.6 in PCF (3.7 not available A.T.T)

Creating app hello-world...
Mapping routes...
Binding services...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 166.02 KiB / 166.02 KiB [===================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee successfully created container for instance 86112031-2d5e-4c57-bc76-6806a1d75271
   Downloading app package...
   Downloaded app package (9.8M)
   -----> Python Buildpack version 1.6.21
   -----> Supplying Python
   -----> Installing python 2.7.15
          Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.15-linux-x64-cflinuxfs2-e0dd33dd.tgz]
   -----> Installing setuptools 40.2.0
          Download [https://buildpacks.cloudfoundry.org/dependencies/setuptools/setuptools-40.2.0-47881d54.zip]
   -----> Installing pip 9.0.3
          Download [https://buildpacks.cloudfoundry.org/dependencies/pip/pip-9.0.3-7bf48f9a.tar.gz]
   -----> Installing pip-pop 0.1.1
          Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Running Pip Install
          Collecting Flask>=0.12 (from -r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting pymysql (from -r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting flask-wtf (from -r /tmp/contents983937053/deps/0/requirements.txt (line 4))
          Collecting flask-sqlalchemy (from -r /tmp/contents983937053/deps/0/requirements.txt (line 5))
          Collecting flask-marshmallow (from -r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting marshmallow-sqlalchemy (from -r /tmp/contents983937053/deps/0/requirements.txt (line 7))
          Collecting Werkzeug>=0.14 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting Jinja2>=2.10 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting itsdangerous>=0.24 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting click>=5.1 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting cryptography (from pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting WTForms (from flask-wtf->-r /tmp/contents983937053/deps/0/requirements.txt (line 4))
          Collecting SQLAlchemy>=0.8.0 (from flask-sqlalchemy->-r /tmp/contents983937053/deps/0/requirements.txt (line 5))
          Collecting marshmallow>=2.0.0 (from flask-marshmallow->-r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting six>=1.9.0 (from flask-marshmallow->-r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting idna>=2.1 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting asn1crypto>=0.21.0 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting cffi!=1.11.3,>=1.7 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
            Could not find a version that satisfies the requirement enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3)) (from versions: )
          No matching distribution found for enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Running pip install without indexes failed. Not all dependencies were vendored. Trying again with indexes.
          Collecting Flask>=0.12 (from -r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting pymysql (from -r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting flask-wtf (from -r /tmp/contents983937053/deps/0/requirements.txt (line 4))
          Collecting flask-sqlalchemy (from -r /tmp/contents983937053/deps/0/requirements.txt (line 5))
          Collecting flask-marshmallow (from -r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting marshmallow-sqlalchemy (from -r /tmp/contents983937053/deps/0/requirements.txt (line 7))
          Collecting Werkzeug>=0.14 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting Jinja2>=2.10 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting itsdangerous>=0.24 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting click>=5.1 (from Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting cryptography (from pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting WTForms (from flask-wtf->-r /tmp/contents983937053/deps/0/requirements.txt (line 4))
          Collecting SQLAlchemy>=0.8.0 (from flask-sqlalchemy->-r /tmp/contents983937053/deps/0/requirements.txt (line 5))
          Collecting marshmallow>=2.0.0 (from flask-marshmallow->-r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting six>=1.9.0 (from flask-marshmallow->-r /tmp/contents983937053/deps/0/requirements.txt (line 6))
          Collecting MarkupSafe>=0.23 (from Jinja2>=2.10->Flask>=0.12->-r /tmp/contents983937053/deps/0/requirements.txt (line 2))
          Collecting idna>=2.1 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting asn1crypto>=0.21.0 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting cffi!=1.11.3,>=1.7 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Collecting enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
            Could not find a version that satisfies the requirement enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3)) (from versions: )
          No matching distribution found for enum34 (from cryptography->pymysql->-r /tmp/contents983937053/deps/0/requirements.txt (line 3))
          Running pip install failed. You need to include all dependencies in the vendor directory.
          **ERROR** Could not install pip packages: Couldn't run pip: exit status 1
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee stopping instance 86112031-2d5e-4c57-bc76-6806a1d75271
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee destroying container for instance 86112031-2d5e-4c57-bc76-6806a1d75271
   Cell a3339c76-e8f2-4291-a1fa-4234b6e955ee successfully destroyed container for instance 86112031-2d5e-4c57-bc76-6806a1d75271
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by anyu** [comment]
Thanks @jmcclenny-epoc! We'll take a look.

**Comment by sclevine** [comment]
@jmcclenny-epoc can you let us know if this is working on `develop`?

**Comment by jmcclenny-epoc** [comment]
@sclevine App is now making it past the buildpack part. Have my own errors to work through with the application itself.

Thanks everyone involved!

**Comment by mguarascio** [comment]
I'm seeing the same error using buildpack 1.6.24, when the buildpack tries to run setup.py on cffi (a transitive dependency of flask-pyoidc). 

Should I open a new issue or would that be fixed as part of this issue?

**Comment by Zanadar** [comment]
@mguarascio Sorry for responding slowly! If you continue to see this, please open a new issue, but refer to this issue.
