### ISSUE TITLE
Update buildpack to new pip version 18.1

### ISSUE THREAD

**Issue by jimenisimo** [cloudfoundry/python-buildpack#128]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

   "name": "IBM Cloud",
   "build": "1.19",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://login.eu-gb.bluemix.net/UAALoginServerWAR",
   "token_endpoint": "https://uaa.eu-gb.bluemix.net",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.106.0",
   "app_ssh_endpoint": "ssh.eu-gb.bluemix.net:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.eu-gb.bluemix.net:443",
   "bits_endpoint": "https://bits-service.eu-gb.bluemix.net",
   "user": "7e0d6ac3-cd08-40fb-b218-6739b22822a5"

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing an application

What was the actual behavior?

When pushing an application I received the following message:

          **You are using pip version 9.0.1, however version 18.1 is available.**
          **You should consider upgrading via the 'pip install --upgrade pip' command.**

Please confirm where necessary:
* [ ] I have included a log output
* [X ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by kardolus** [comment]
`pip 18` introduces some breaking changes making it incompatible with a certain tool we use called `pip-pop`. For now we will have to stick with `pip 9`

**Comment by jimenisimo** [comment]
Ok, but how can I get rid of that Error, that doesn't allow me to deploy my Rest Api in Bluemix. Is there a way to make it work with pip 9.0.1?
Or should I switch to another cloud service?

**Comment by ibm-cio-rtp** [comment]
This is a blocker for me too.

**Comment by thedickens** [comment]
@cf-gitbot Is there a workaround for this on bluemix or are their any plans to upgrade pip ?
