### ISSUE TITLE
Pre and post compile hooks aren't capturing stderr

### ISSUE THREAD

**Issue by amhuber** [cloudfoundry/python-buildpack#129]
What version of the buildpack you are using?
v1.6.27

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to debug an issue in a pre-compile script.

What did you expect to happen?
Expected to see output from both stdout and stderr from the pre-compile script

What was the actual behavior?
Only stdout output was capture by staging.

The code running the pre and post compile hooks is only capturing stdout.  It looks like changing this line to use CombinedOutput() instead of Output() will easily fix the issue.

https://github.com/cloudfoundry/python-buildpack/blob/master/src/python/hooks/hooks_app.go#L55
https://golang.org/pkg/os/exec/#Cmd.CombinedOutput

**Comment by dwillist** [comment]
@amhuber Thanks for opening a PR, We will prioritize, feel free to keep tabs on it [here](https://www.pivotaltracker.com/story/show/158812800)
