### ISSUE TITLE
Are Flask apps supported?

### ISSUE THREAD

**Issue by monfresh** [cloudfoundry/python-buildpack#13]
Hi,

I'm trying to deploy a Flask app to Cloud Foundry, and I've tried doing it both ways (disconnected environment instructions and regular instructions), but it's failing with the same error. I've successfully deployed the same app to Heroku. Here is the app: https://github.com/18F/project-monitor

Here is the last part of the log:
```bash
015-03-13T16:29:54.17-0400 [STG/0]      OUT        Successfully installed Jinja2-2.7.3 Project-Monitor-0.0.0 Werkzeug-0.10.1 flask-0.10.1 future-0.14.3 gunicorn-19.3.0 httmock-1.2.3 itsdangerous-0.24 markupsafe-0.23 psycopg2-2.6 requests-2.2.1
2015-03-13T16:29:55.39-0400 [STG/0]      ERR /tmp/buildpacks/buildpack-python/bin/compile: line 230: CF_STACK: unbound variable
2015-03-13T16:29:55.39-0400 [STG/0]      OUT Staging failed: Buildpack compilation step failed
```

Thanks!

**Comment by jtarchie** [comment]
@monfresh, we are rolling out new changes for a new cf-release, the buildpack on master is not guaranteed to be backwards compatible with older versions of CF.

You can either use the stable buildpack with your CF deployment[1] or point to the tagged version from the git[2] repo.

[1] `cf push app -b python_buildpack`
[2] `cf push app -b https://github.com/cloudfoundry/python-buildpack#v1.1.2`

**Comment by monfresh** [comment]
Thanks! That worked.

**Comment by jtarchie** [comment]
Thanks for letting us know!
