### ISSUE TITLE
Python app failing with error "Cloud foundry white list request"

### ISSUE THREAD

**Issue by nakultyagi28** [cloudfoundry/python-buildpack#132]
@egmanoharan @jfeeny were you guys able to fix the issue ?

Continuing on the existing issue https://github.com/cloudfoundry/python-buildpack/issues/109

We are facing the same issue while pushing all the python apps.

we are using cf version 6.38.0+7ddf0aadd.2018-08-07

We are using the python-buildpack-v1.5.26.zip

Staging app and tracing logs...
   Downloading python_buildpack...
   Downloaded python_buildpack
   Creating container
   Successfully created container
   Downloading app package...
   Downloaded app package (1.4K)
   -------> Buildpack version 1.5.26
    !     Warning: Your application is missing a Procfile. This file tells Cloud Foundry how to run your application.
    !     Learn more: https://docs.cloudfoundry.org/buildpacks/prod-server.html#procfile
   -----> Installing python-2.7.14
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/python/python-2.7.14-linux-x64-970d20be.tgz]
   -----> Installing Setuptools (32.1.0)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/setuptools/setuptools-32.1.0-44054eaa.tar.gz]
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip/pip-9.0.1-35f01da3.tar.gz]
   -----> Installing Pip (9.0.1)
   -----> Installing pip-pop (0.1.1)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.1-d410583a.tar.gz]
   -----> Installing pipenv (4.0.1)
   Downloaded [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pipenv/pipenv-4.0.1-148f753f.tar.gz]
        $ pip install -r requirements.txt
          Collecting Flask (from -r requirements.txt (line 1))
            Could not fetch URL https://pypi.python.org/simple/flask/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) - skipping
   No matching distribution found for Flask (from -r requirements.txt (line 1))
Error staging application: App staging failed in the buildpack compile phase
FAILED

**Comment by kardolus** [comment]
Hey @egmanoharan or @nakultyagi28 - does one of you happen to have a simple test app that we could use in order to reproduce this? Would be super useful to kick start our research. 

Thanks for reporting!

**Comment by kardolus** [comment]
Also, do you get the same issue when u try and push using `cf p <app_name> -b https://github.com/cloudfoundry/python-buildpack` ? Just to see if our latest buildpack has the same issue for you guys.

**Comment by 1kaushik1** [comment]
@kardolus We recently found out that the issue seems to be on a cloud foundry instance that's deployed on a specific network.
For example our cloud foundry instance that was deployed on AWS seems to do good with the existing python buildpacks. But one of our other cloud foundry instances thats deployed on a private data center is having problems downloading dependencies. we even tried passing the cert.pem file while attempting a download.
Could it be that the infra network is somehow disallowing the download or not allowing the certificates to be passed? Could that be a possibility ?

**Comment by chhhavi** [comment]
@1kaushik1 As a workaround to the CF that has problems downloading dependencies, you could vendor your dependencies into the app (https://docs.cloudfoundry.org/buildpacks/python/index.html#vendoring). Could you please give us a sample application, and paste the complete application logs from the cf push?

**Comment by 1kaushik1** [comment]
@chhhavi Thankyou for you suggestion, the work around worked good.

And for a sample application i am trying https://github.com/swisscom/cf-sample-app-python.
