### ISSUE TITLE
It is time to stop defaulting to legacy Python

### ISSUE THREAD

**Issue by cclauss** [cloudfoundry/python-buildpack#135]
Another attempt at #19, #74, #113...

With 234 days remaining until Python 2 end of life, it is time to switch the runtime default from legacy Python to Python 3.  When the default is switched, it would be better to move a current Python release (3.7.x) and not some old version like Python 3.5.x or 3.6.x because changing the default is a touchy change.  https://twitter.com/raymondh/status/1080961135493316608

Typo here: https://github.com/cloudfoundry/python-buildpack/blob/develop/manifest.yml#L5

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
https://github.com/cloudfoundry/python-buildpack

What version of the buildpack you are using?
https://github.com/cloudfoundry/python-buildpack/issues/new

If you were attempting to accomplish a task, what was it you were attempting to do?
Create a new project.  I got NameErrors on both _async_ and _await_.

What did you expect to happen?
I would be able to use f"strings" and asyncio.

What was the actual behavior?
__import http.server__ failed.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
The next-generation (Cloud Native Buildpacks: buildpacks.io) version of this buildpack will provide Python 3 by default. We plan to make an announcement about this on the cf-dev mailing list soon. We have a compatibility layer that will allow the new CNBs to run on existing Cloud Foundry foundations, so the new version of this buildpack should be available to all current users well before Python 2 hits EOL.

Development is happening here:
https://github.com/cloudfoundry/python-cnb
https://github.com/cloudfoundry/pip-cnb
https://github.com/cloudfoundry/cnb2cf
