### ISSUE TITLE
Why default to pip 9.0.3 when current is pip 19.1.1?

### ISSUE THREAD

**Issue by cclauss** [cloudfoundry/python-buildpack#136]
There has been a lot of progress on [__pip__](https://pypi.org/project/pip/) and on PyPI in general in the past year.  Why does this buildpack default to a pip that is more than a year old?

https://github.com/cloudfoundry/python-buildpack/blob/develop/manifest.yml#L61

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
https://github.com/cloudfoundry/python-buildpack

What version of the buildpack you are using?
https://github.com/cloudfoundry/python-buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
Create a Python webapp.  

What did you expect to happen?
I could use my __pyproject.toml__ file.

What was the actual behavior?
pip needed to be upgraded to use __pyproject.toml__.

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by sclevine** [comment]
This buildpack no longer provides a separate copy of pip from the version bundled in each Python version. That manifest.yml entry was left in by mistake, and we will remove it before the next release is cut. Thanks for catching that!

While this buildpack does provide recent versions of pip with recent versions of Python, it doesn't explicitly support Poetry's usage of pyproject.toml to specify dependencies. For the next-generation (Cloud Native Buildpacks: buildpacks.io) version of this buildpack, we plan to support Poetry as well.
