### ISSUE TITLE
PCF deployment issue with boto3

### ISSUE THREAD

**Issue by hltate** [cloudfoundry/python-buildpack#137]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "Pivotal Application Service",
   "build": "2.3.3",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-3/pcf-release-notes/runtime-rn.html",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.120.0",
}

What version of the buildpack you are using?
python_buildpack-cached-cflinuxfs3-v1.6.28.zip

If you were attempting to accomplish a task, what was it you were attempting to do?
deploy app

What did you expect to happen?
App to deploy

What was the actual behavior?
App fails to deploy when boto3 is included in requirements.txt and vendor folder. 
To narrow down the issue, a simple file was created that does not make a boto call.  Just including boto3 in the requirements.txt will prevent the app from successfully deploying to PCF.  If boto is removed from the requirements.txt the app will deploy.   Apps have been deployed using boto3 to PCF without issue.  This behavior was noticed last Friday.  In previous deployments, setuptools was not required to be in the vendor folder.  When a verison of setuptools supported by the buildpack is included,  wheel cannot be found. 

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x
[requirements.txt](https://github.com/cloudfoundry/python-buildpack/files/3254143/requirements.txt)
[runtime.txt](https://github.com/cloudfoundry/python-buildpack/files/3254144/runtime.txt)
[error_log__no_setuptools.txt](https://github.com/cloudfoundry/python-buildpack/files/3254172/error_log__no_setuptools.txt)
[error_log__with_setuptools.txt](https://github.com/cloudfoundry/python-buildpack/files/3254173/error_log__with_setuptools.txt)
] I have included steps for reproduction

manifest.yml
applications:
- name: S3Copytest1
  buildpack: python_buildpack
  memory: 1G
  disk_quota: 1G
  no-route: true
  health-check-type: process
  stack: cflinuxfs3
  command: python s3copytest1.py

s3copytest1.py
import os
import sys
import time

def ods_list():
    try:
        while True:
            print ('got here....')
            time.sleep(120)
    except Exception as e:
        print ("****** ERROR ******" + str(e))

    return 

#main entry point in to the application
if __name__ == '__main__':
    print("about to start processing...")
    print("listing...")
    ods_list()
    sys.exit()

**Comment by kardolus** [comment]
@hltate thanks! we added this to our backlog

**Comment by kardolus** [comment]
@hltate I think this commit should fix your problem. Right now its on develop: https://github.com/cloudfoundry/python-buildpack/commit/eb4881b8ad79215b196af15cc1e1b7927fda1304

Will release soon! :)
