### ISSUE TITLE
Intermittent "Staging Time Expired" errors after a few seconds

### ISSUE THREAD

**Issue by dirkjot** [cloudfoundry/python-buildpack#139]
# What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

PWS current, ie 
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.136.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "dcdd2866-0f1f-44c3-83ff-6c3dcacdea5a"
}
cf version 6.45.0+5f9ff16f9.2019-06-03

# What version of the buildpack you are using?

PWS Current, I double checked I was on cflinuxfs3

python_buildpack             7          true      false    python_buildpack-cached-cflinuxfs3-v1.6.34.zip        cflinuxfs3

# If you were attempting to accomplish a task, what was it you were attempting to do?

cf push -f manifest.yml

# What did you expect to happen?

Successful push

# What was the actual behavior?

A successful push happens sometimes, I think.  It also happens when I first delete the app and it happens when I push to a fresh app.  Updating an existing app will sometimes/most of the times trigger the failure. 

Logs below, essentially `Error staging application: StagingTimeExpired` .  I did three runs, see below, and it shows up in different places, always within 60s.  I also pushed with `CF_STAGING_TIMEOUT=15 cf push -f manifest.yml `, same deal. 

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

### LOGS

± |master U:1 ✗| → cf push -f manifest.yml
Pushing from manifest to org dirk / space workspace as djanssen@pivotal.io...
Using manifest file manifest.yml
Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

Getting app info...
Updating app with these attributes...
  name:                tikkat
  path:                /Users/dpj/workspace/tikkat/src
  buildpacks:
    python_buildpack
  command:             python tikkat.py
  disk quota:          1G
  health check type:   process
  instances:           1
  memory:              256M
  stack:               cflinuxfs3
  env:
    AIRTABLE_API_KEY
    AIRTABLE_BASE
    BASE_ACTIONS
    BASE_TICKETS
    SLACK_BOT_TOKEN
    SLACK_SIGNING_SECRET
    SLACK_TOKEN
    VERIFICATION_TOKEN
  routes:
    tikkat.cfapps.io

Updating app tikkat...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 43.77 KiB / 43.77 KiB [=============================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Stopping app...

Staging app and tracing logs...
Error staging application: StagingTimeExpired
FAILED

 2019-06-17 19:39:19 ⌚ ruby 2.4.2p198 office-5-8 in ~/workspace/tikkat/src
± |master U:1 ✗| → cf push -f manifest.yml
Pushing from manifest to org dirk / space workspace as djanssen@pivotal.io...
Using manifest file manifest.yml
Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

Getting app info...
Updating app with these attributes...
  name:                tikkat
  path:                /Users/dpj/workspace/tikkat/src
  buildpacks:
    python_buildpack
  command:             python tikkat.py
  disk quota:          1G
  health check type:   process
  instances:           1
  memory:              256M
  stack:               cflinuxfs3
  env:
    AIRTABLE_API_KEY
    AIRTABLE_BASE
    BASE_ACTIONS
    BASE_TICKETS
    SLACK_BOT_TOKEN
    SLACK_SIGNING_SECRET
    SLACK_TOKEN
    VERIFICATION_TOKEN
  routes:
    tikkat.cfapps.io

Updating app tikkat...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 43.77 KiB / 43.77 KiB [=============================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Stopping app...
          Collecting autopep8==1.4.4 (from -r /tmp/app/requirements.txt (line 9))
            Downloading https://files.pythonhosted.org/packages/45/f3/24b437da561b6af4840c871fbbda32889ca304fc1f7b6cc3ada8b09f394a/autopep8-1.4.4.tar.gz (114kB)

Staging app and tracing logs...
          Collecting certifi==2019.3.9 (from -r /tmp/app/requirements.txt (line 10))
   Cell 18751cdc-f831-44cf-afdf-5e7730e7444e stopping instance 47c37e9f-dd00-46c6-b944-4475eaef0c21
            Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
          Collecting cffi==1.12.3 (from -r /tmp/app/requirements.txt (line 11))
            Downloading https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl (430kB)
          Collecting chardet==3.0.4 (from -r /tmp/app/requirements.txt (line 12))
            Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
          Collecting Click==7.0 (from -r /tmp/app/requirements.txt (line 13))
            Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
          Collecting Flask==1.0.3 (from -r /tmp/app/requirements.txt (line 14))
            Downloading https://files.pythonhosted.org/packages/9a/74/670ae9737d14114753b8c8fdf2e8bd212a05d3b361ab15b44937dfd40985/Flask-1.0.3-py2.py3-none-any.whl (92kB)
          Collecting idna==2.8 (from -r /tmp/app/requirements.txt (line 15))
            Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
          Collecting idna-ssl==1.1.0 (from -r /tmp/app/requirements.txt (line 16))
            Downloading https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
Error staging application: StagingTimeExpired
FAILED

 2019-06-17 19:39:32 ⌚ ruby 2.4.2p198 office-5-8 in ~/workspace/tikkat/src
± |master U:1 ✗| → cf push -f manifest.yml
Pushing from manifest to org dirk / space workspace as djanssen@pivotal.io...
Using manifest file manifest.yml
Deprecation warning: Use of 'buildpack' attribute in manifest is deprecated in favor of 'buildpacks'. Please see http://docs.cloudfoundry.org/devguide/deploy-apps/manifest.html#deprecated for alternatives and other app manifest deprecations. This feature will be removed in the future.

Getting app info...
Updating app with these attributes...
  name:                tikkat
  path:                /Users/dpj/workspace/tikkat/src
  buildpacks:
    python_buildpack
  command:             python tikkat.py
  disk quota:          1G
  health check type:   process
  instances:           1
  memory:              256M
  stack:               cflinuxfs3
  env:
    AIRTABLE_API_KEY
    AIRTABLE_BASE
    BASE_ACTIONS
    BASE_TICKETS
    SLACK_BOT_TOKEN
    SLACK_SIGNING_SECRET
    SLACK_TOKEN
    VERIFICATION_TOKEN
  routes:
    tikkat.cfapps.io

Updating app tikkat...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 43.77 KiB / 43.77 KiB [=============================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Stopping app...

Staging app and tracing logs...
   Cell acc2507a-5cc5-474d-ab70-94b3d59fd31b stopping instance 0f1bc066-1a7c-464f-ac17-b225e25cad04
          Collecting certifi==2019.3.9 (from -r /tmp/app/requirements.txt (line 10))
            Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
          Collecting cffi==1.12.3 (from -r /tmp/app/requirements.txt (line 11))
            Downloading https://files.pythonhosted.org/packages/5f/bf/6aa1925384c23ffeb579e97a5569eb9abce41b6310b329352b8252cee1c3/cffi-1.12.3-cp36-cp36m-manylinux1_x86_64.whl (430kB)
          Collecting chardet==3.0.4 (from -r /tmp/app/requirements.txt (line 12))
            Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
          Collecting Click==7.0 (from -r /tmp/app/requirements.txt (line 13))
            Downloading https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl (81kB)
          Collecting Flask==1.0.3 (from -r /tmp/app/requirements.txt (line 14))
            Downloading https://files.pythonhosted.org/packages/9a/74/670ae9737d14114753b8c8fdf2e8bd212a05d3b361ab15b44937dfd40985/Flask-1.0.3-py2.py3-none-any.whl (92kB)
          Collecting idna==2.8 (from -r /tmp/app/requirements.txt (line 15))
            Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
          Collecting idna-ssl==1.1.0 (from -r /tmp/app/requirements.txt (line 16))
            Downloading https://files.pythonhosted.org/packages/46/03/07c4894aae38b0de52b52586b24bf189bb83e4ddabfe2e2c8f2419eec6f4/idna-ssl-1.1.0.tar.gz
   Cell 18751cdc-f831-44cf-afdf-5e7730e7444e successfully destroyed container for instance 47c37e9f-dd00-46c6-b944-4475eaef0c21
          Collecting importlib-metadata==0.15 (from -r /tmp/app/requirements.txt (line 17))
Error staging application: StagingTimeExpired
FAILED

**Comment by Zanadar** [comment]
First off, I'd recommend vendoring your dependencies, which is documented here: https://docs.cloudfoundry.org/buildpacks/python/index.html#vendoring 
Also, @dirkjot Can we have some sort of sample app, including representative requirements.txt

**Comment by dirkjot** [comment]
Thanks for the recommendation.  It may work, but I feel vendoring should
not be necessary when pushing to PWS.

You can find the app here: github.com/dirkjot/tikkat  just 'cd src; cf push
-f manifest'  Note that the issue is intermittent, and only shows up when
you push a new version.   Also note that the app will crash because it
lacks credentials, my bug is about cf push failing.

FYI:  I have left Pivotal last week (for an exciting new job, but I am
still sad about leaving you guys).  This means I will soon not be able to
push to PWS anymore.

Dirk

**Comment by Zanadar** [comment]
I suspect its the inclusion of pandas. compiling all that fortan code has timed out other apps. we're tracking this as an issue. closing for now.
