### ISSUE TITLE
IMPORTANT NOTICE: End of support for Python versions 3.4.x after 2019-11-18

### ISSUE THREAD

**Issue by shanks3012** [cloudfoundry/python-buildpack#146]
The first release of the Python buildpack after November 18, 2019 will no longer include Python versions 3.4.x These Python versions will no longer be supported upstream.[1] Please migrate your Python apps to supported versions of Python before that time.

Note: Unless you are manually specifying a version of Python for the buildpack to use, or you have customized your Python buildpack, no action is required.

[1] https://www.python.org/downloads/release/python-343/

**Comment by sclevine** [comment]
@shanks3012 reminder about this scheduled deprecation
