### ISSUE TITLE
Support manylinux10 ABI in 3.6.x buildpack by updating to pip 19.x

### ISSUE THREAD

**Issue by mhaas-work** [cloudfoundry/python-buildpack#147]
# Versions

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```
{
   "name": "",
   "build": "",
   "support": "",
   "version": 0,
   "description": "Cloud Foundry at SAP Cloud Platform",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "api_version": "2.141.0",
   "osbapi_version": "2.15",

}
```

```
➜  ~ cf version
cf version 6.46.0+29d6257f1.2019-07-09
```

# What version of the buildpack you are using?

1.6.36

# If you were attempting to accomplish a task, what was it you were attempting to do?

I am trying to `cf push` an app with vendored dependencies. These vendored dependencies were downloaded using `pip` version `19.x`. Among these vendored dependencies was `cryptography-2.8-cp34-abi3-manylinux2010_x86_64.whl`

# What did you expect to happen?

I expected the push to succeed.

# What was the actual behavior?

The `push` failed because the vendored dependencies could not be installed:

```
[2019-10-20T21:56:08.834Z]        Collecting cryptography (from sap-xssec==2.0.6->meh-commons==2.0.26->-r /tmp/app/requirements.txt (line 14))
[2019-10-20T21:56:08.834Z]          Could not find a version that satisfies the requirement cryptography (from sap-xssec==2.0.6->meh-commons==2.0.26->-r /tmp/app/requirements.txt (line 14)) (from versions: )
[2019-10-20T21:56:08.834Z]        No matching distribution found for cryptography (from sap-xssec==2.0.6->meh-commons==2.0.26->-r /tmp/app/requirements.txt (line 14))
```

I believe this problem occurs because the buildpack mentioned uses an older version of pip (`18.x`), which does not have support for the `manylinux2010` ABI (see [PEP 571](https://www.python.org/dev/peps/pep-0571/). Support for this ABI was introduced in `pip 19.0` according to the [pip changelog](https://pip.pypa.io/en/stable/news/#id146).

Thus, packages vendored with a newer version of pip cannot be used with the current version of the Python buildpack. This recently started occuring ion my project due to `2.8` release of the cryptography package, which now provides `manylinux2010` along the old `manylinux1` wheels.

# Steps to reproduce:
* Use python 3.6 buildpack 
* Add manylinux2010 wheel to vendor/
* Attempt to push app and install this dependency

# Suggested resolution

Update pip to 19.x.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by dfreilich** [comment]
Hey @mhaas-work , thanks for posting the issue! Python `3.8` comes with pip `19`, so that should hopefully solve your problem. I'm closing it for now, but feel free to reopen it if it doesn't help!

**Comment by mhaas-work** [comment]
Hi @dfreilich, the problem is that I cannot upgrade to Python 3.7 or 3.8 due to some binary dependencies - so the ability to update to a newer pip would be useful.

**Comment by dfreilich** [comment]
Hmm ok. We're focusing more on our development of the CNBs, and we can take that as a feature request in our [pip-cnb](https://github.com/cloudfoundry/pip-cnb), but I don't think that this will be done in this buildpack. I'll transfer it there.
