### ISSUE TITLE
Pip-pop version in the manifest is 0.1.3, while 0.1.4 is being downloaded

### ISSUE THREAD

**Issue by mudler** [cloudfoundry/python-buildpack#151]
Hi, 

It seems the version wasn't  bumped, while the referenced tarball was.

https://github.com/cloudfoundry/python-buildpack/blob/6465baa793df80a65c20ab626447992fa845d0c1/manifest.yml#L68

cc: @jimmykarily

**Comment by dfreilich** [comment]
Hey @mudler , thanks for pointing that out! We'll change that ASAP on develop, and get it to Master in the next release.

**Comment by shanks3012** [comment]
@mudler The change is currently on the develop branch and will find its way to master early next week. As we always want to maintain the latest patch versions, pip-pop is now at 0.1.4 in manifest along with downloading 0.1.4.

Closing the issue. Thanks for pointing this out!

**Comment by mudler** [comment]
Thanks for the quick fix!
