### ISSUE TITLE
 Could not install pip-pop - 0.1.3 : exit status 1

### ISSUE THREAD

**Issue by narraraveendrababu** [cloudfoundry/python-buildpack#154]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "IBM Cloud",
   "build": "v11.2.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
   "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
   "api_version": "2.142.0",
   "osbapi_version": "2.15",
   "user": "23ff823c-b2f7-486c-9d2e-1ae59d7af5f1"
}

What version of the buildpack you are using?

https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.34/python-buildpack-cflinuxfs3-v1.6.34.zip

If you were attempting to accomplish a task, what was it you were attempting to do?
Trying to push the application with all the dependencies are pre-installed.

Mainfest.yml 

---
applications:
 - name: call-home-last-contact-warning-development
   instances: 1
   memory: 2048M
   timeout: 180
   #buildpack: python_buildpack
   buildpack: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.34/python-buildpack-cflinuxfs3-v1.6.34.zip
   command: python lastContactWarning.py

What did you expect to happen?
Successfully push application with out any build failures.

What was the actual behavior?
Failing install pip-pop - 0.1.3

Updating app with these attributes...
  name:                   call-home-last-contact-warning-development
  path:                   /Users/raveendra/Desktop/call-home-dev/cdo-migration/testes-changes/last_contact_warn
  buildpacks:
-   https://github.com/cloudfoundry/python-buildpack#v.1.6.34
+   https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.34/python-buildpack-cflinuxfs3-v1.6.34.zip
  command:                python lastContactWarning.py
  disk quota:             1G
  health check timeout:   180
  health check type:      process
  instances:              1
  memory:                 2G
  stack:                  cflinuxfs3
  env:
    PIP_TARGET
  routes:
    call-home-last-contact-warning-development.mybluemix.net

Updating app call-home-last-contact-warning-development...
Mapping routes...
Comparing local files to remote cache...
Packaging files to upload...
Uploading files...
 7.99 KiB / 7.99 KiB [==================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

Staging app and tracing logs...
   Cell fda25406-d74a-4aa0-aedf-5cdeb0817bf3 creating container for instance 6b3c92b5-105d-423f-aabc-e858dd1082cd
   Cell fda25406-d74a-4aa0-aedf-5cdeb0817bf3 successfully created container for instance 6b3c92b5-105d-423f-aabc-e858dd1082cd
   Downloading app package...
   Downloaded app package (8K)
   Downloaded buildpack `https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.34/python-buildpack-cflinuxfs3-v1.6.34.zip` (5M)
   -----> Python Buildpack version 1.6.34
   -----> Supplying Python
   -----> Installing python 3.6.7
          Download [https://buildpacks.cloudfoundry.org/dependencies/python/python-3.6.7-linux-x64-cflinuxfs3-70a1f47b.tgz]
          **WARNING** A newer version of python is available in this buildpack. Please adjust your app to use version 3.6.8 instead of version 3.6.7 as soon as possible. Old versions of python are only provided to assist in migrating to newer versions.
   -----> Installing pip-pop 0.1.3
          Download [https://buildpacks.cloudfoundry.org/dependencies/manual-binaries/pip-pop/pip-pop-0.1.3-fc106ef6.tar.gz]
          **ERROR** Could not install pip pop: exit status 1
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Cell fda25406-d74a-4aa0-aedf-5cdeb0817bf3 stopping instance 6b3c92b5-105d-423f-aabc-e858dd1082cd
Error staging application: App staging failed in the buildpack compile phase
FAILED

Please confirm where necessary:
* [yes ] I have included a log output
* [ yes] My log includes an error message
* [yes ] I have included steps for reproduction

**Comment by narraraveendrababu** [comment]
could you please any update on this. My production container having problem.

**Comment by ryanmoran** [comment]
@narraraveendrababu We've been unable to replicate this. Is there anything special about your environment or application?

**Comment by thitch97** [comment]
We are going to close this issue for now. Please feel free to reopen this with more reproduction details.
