### ISSUE TITLE
PIP fails to install latest version

### ISSUE THREAD

**Issue by EdukondaluK** [cloudfoundry/python-buildpack#160]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "Pivotal Application Service",
   "build": "2.4.13-build.2",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-4/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sausmpc01.pcf.dell.com",
   "token_endpoint": "https://uaa.sausmpc01.pcf.dell.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "ssh.sausmpc01.pcf.dell.com:2222",
   "app_ssh_host_key_fingerprint": "fa:7b:99:ab:0f:92:a3:32:90:46:bd:0d:7f:63:bc:3b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sausmpc01.pcf.dell.com:443",
   "api_version": "2.125.0",
   "osbapi_version": "2.14",
   "routing_endpoint": "https://api.sausmpc01.pcf.dell.com/routing",
   "user": "f9a1a4d4-74b6-446c-8f88-cda4b9d0fb64"
}

cf version 6.49.0+d0dfa93bb.2020-01-07
What version of the buildpack you are using?
**dicf_python_buildpack_174_cflinuxfs3**
If you were attempting to accomplish a task, what was it you were attempting to do?
 You are using pip version 18.1, however version 20.0.2 is available.

What did you expect to happen?

PIP version should come latest one

What was the actual behavior?
 it comes older version

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ryanmoran** [comment]
@EdukondaluK the buildpack does not install the latest version of `pip`. It uses the version that was included with the release of Python that you are using.
