### ISSUE TITLE
Support poetry (pyproject.toml)

### ISSUE THREAD

**Issue by eruvanos** [cloudfoundry/python-buildpack#162]
Hi,

as pipenv seems to be kind of inactive (last release from 26 Nov 2018),
people are migrating to tools like [Poetry](https://python-poetry.org/) or [Flit](https://flit.readthedocs.io/en/latest/), that are using PEP 517 & 518.

There are a few things I think could be really useful:

- Read requirements from `pyproject.toml`
- Read requirements (with version lock) from poetry.lock if available/ use `poetry install`
- Read the Python version from `pyproject.toml`

What do you thing?

**Comment by kvedurmu** [comment]
Hey @eruvanos this is something that we'll consider adding to the Python CNB (something like a poetry-cnb). I'm going to close out this issue but feel free to follow along on this Python CNB [feature request](https://github.com/cloudfoundry/python-cnb/issues/4)
