### ISSUE TITLE
Supplying conda is failing without runtime.txt [v.1.7.8]

### ISSUE THREAD

**Issue by tbehnke** [cloudfoundry/python-buildpack#164]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

{
   "name": "",
   "build": "",
   "support": "*****",
   "version": 0,
   "description": "****",
   "authorization_endpoint": "*****"
   "token_endpoint": "*****",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "*****:2222",
   "app_ssh_host_key_fingerprint": "****",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "****",
   "api_version": "2.146.0",
   "osbapi_version": "2.15",
   "user": "****"
}
cf version 6.44.0+5de0f0d02.2019-05-01

What version of the buildpack you are using?
1.7.8

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing a CF app using an environment.yml file that specifies the Python version & dependencies.

What did you expect to happen?
Miniconda3 should be installed by the default, because miniconda2 was removed in 1.7.7.

What was the actual behavior?
The buildpack was trying to install miniconda2. Here's the log:
Staging app and tracing logs...
   Downloading python_buildpack...
   Downloaded python_buildpack
   Cell 88e34946-a6b8-4b6c-91dc-99389c9e4b9e creating container for instance 7e62e9c1-e5bd-4533-909e-7a8e19cd791b
   Cell 88e34946-a6b8-4b6c-91dc-99389c9e4b9e successfully created container for instance 7e62e9c1-e5bd-4533-909e-7a8e19cd791b
   Downloading app package...
   Downloaded app package (68.4M)
   -----> Python Buildpack version 1.7.8
   -----> Supplying conda
          **ERROR** Could not install conda: Error downloading miniconda: no versions of miniconda2 found
   Failed to compile droplet: Failed to run all supply scripts: exit status 14
   Exit status 223
   Cell 88e34946-a6b8-4b6c-91dc-99389c9e4b9e stopping instance 7e62e9c1-e5bd-4533-909e-7a8e19cd791b
   Cell 88e34946-a6b8-4b6c-91dc-99389c9e4b9e destroying container for instance 7e62e9c1-e5bd-4533-909e-7a8e19cd791b
Error staging application: App staging failed in the buildpack compile phase
FAILED

Perhaps this line should be changed:
https://github.com/cloudfoundry/python-buildpack/blob/82e09344e877296063a5c864ee466c7015904dd6/src/python/conda/conda.go#L90

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [] I have included steps for reproduction

**Comment by SanjivShenoy** [comment]
Hey guys,
I am facing the same issue.
Can you please tell me what needs to be written in runtime.txt to make it work?

**Comment by sushanthmangalore** [comment]
Was able to push the app by creating runtime.txt in the application's base directory and specifying the Python version in it.

**Comment by SanjivShenoy** [comment]
@sushanthmangalore, it worked! Thanks a lot!

**Comment by gitricko** [comment]
When is this problem to be resolve? I realized this too by trial and error. Wish I saw this earlier

**Comment by kvedurmu** [comment]
This issue has been fixed in https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.16. Closing this.
