### ISSUE TITLE
Poetry support

### ISSUE THREAD

**Issue by zdog234** [cloudfoundry/python-buildpack#165]
Hi, I haven't been able to find any issues mentioning this, and I don't see any mention of this in the documentation.

It'd be really cool to support [poetry](https://github.com/python-poetry/poetry) for dependency management. It seems to be about as popular as pipenv, depending on which domain you're considering, and I personally prefer it. I'd definitely be up for putting together a PR to add support for this, if it seems like it's worthwhile to include.

**Comment by kvedurmu** [comment]
Hey @zdog234! We've gotten a lot of requests for this in the past, and poetry support is something that we will look into adding in our Python Cloud Native Buildpack (see https://github.com/cloudfoundry/python-cnb/issues/4). 

Our team has reduced our investment in feature additions to CF Buildpacks and has shifted focus to implementing Cloud Native Buildpacks for the Paketo Buildpacks project (https://paketo.io). While we'd welcome a PR for this in the CF Buildpack, it will take us a while to get to reviewing. Any chance you're up for working with us to build a Poetry CNB to support this? If so, let's close this issue out and take our conversation to https://github.com/cloudfoundry/python-cnb/issues/4.

**Comment by zdog234** [comment]
Yeah, I'd definitely be up for working there. I'm a bit new to CF -- our team just decided to start deploying things into an on-prem CF instance. Are cloud-native buildpacks available in on-prem installations? I think I'd rather work on a PR that I'd eventually benefit from, for selfish reasons.

Thanks!

**Comment by kvedurmu** [comment]
So, Cloud Native Buildpacks are the next generation of Buildpack offerings that generate container images that can be deployed on k8s. CNBs will not work as-is on CF foundations, but our team has built tooling to convert a Cloud Native Buildpack into a CF-Compatible Cloud Native Buildpack. These CF-Compatible CNBs can be added onto CF foundations via existing CF CLI commands (e.g `update-buildpack` `create-buildpack`). If you're interested, have a look at the Node JS CNB, which we've already done this for (https://github.com/cloudfoundry/nodejs-cnb/releases). 

Totally understand that you're new to CF and a PR into an existing codebase would be easier :). I'd still encourage you to take a stab at attempting to build a Poetry CNB, as this will have much greater adoption by the broader buildpack community. We can definitely help out with making the Poetry CNB compatible on CF. If you're curious, give this tutorial on [building a cloud native buildpack](https://paketo.io/docs/create-paketo-buildpack/) a read and join us on [slack](https://slack.paketo.io) to ask any questions.

**Comment by mburszley** [comment]
@kvedurmu Speaking as a customer of Pivotal CloudFoundry on-prem, I'm pretty certain my corporation has no plans to migrate to CNB.  I'm in favor of having this contribution to the buildpack be for CF as well, especially with the slow release cycle I see internally.

**Comment by FelixKJose** [comment]
Any updates on the Poetry support in CF?

**Comment by eruvanos** [comment]
As a workaround I recommend to add a `requirements.txt` file with 
```
./
```
in it.

**Comment by menehune23** [comment]
@zdog234 I'm closing this issue as it's not likely to be done by our team for the CF buildpack (due to the focus on the [Paketo Python buildpack](https://github.com/paketo-buildpacks/python)). That said, we'd be happy to take a look at a PR for this repo if you'd like to have a whack at it.

**Comment by ZPascal** [comment]
Hi @znd4, 

the following [PR](https://github.com/cloudfoundry/python-buildpack/pull/1181) should fix the issue.
