### ISSUE TITLE
Please support independent pip versions.

### ISSUE THREAD

**Issue by mhaas** [cloudfoundry/python-buildpack#172]
*Have removed the template, since this is a feature request*

I have raised this request in the past, when it was moved to https://github.com/cloudfoundry/pip-cnb/issues/2. Now, there is a related issue again in this repository: https://github.com/cloudfoundry/python-buildpack/issues/168.

In this issue, I want to make the case **why** I think having the pip version decoupled from the Python version is a great idea and will bring value.

Pip is developed independently of Python and updated more often.

Many packages out there provide wheels which are simply not compatible with older versions of pip. My example here is Tensorflow. With Tensorflow 1.15, the published wheels switched from the `manylinux1` platform tag to the `manylinux2010` platform. There is no way of installing these wheels with the Python 3.6.x buildpack, because pip 18.x simply cannot handle this platform. Building Tensorflow from source is not an option right now as it is a rather involved process.

As a result, I decided to move to Python 3.7 because this will give me Pip 19.x inside the buildpack. Due to issues in [Pip](https://github.com/pypa/pip/issues/8302) and the [buildpack](https://github.com/cloudfoundry/python-buildpack/issues/171), this was a bit bumpy. Now, imagine there are future improvements in pip - I will not be able to consume these improvements easily. Pip is stuck at an older version.

Now, imagine there is a security issue in your favorite dependency and you would like to upgrade to a fixed version. Now, if the fixed versions are only available with a new and unsupported `platform` tag, you are stuck - nothing short of upgrading your entire Python stack will solve this.

My points here are that the hardwired `pip` makes it impossible to upgrade to improved versions of pip as well as updating dependencies in some cases.

This is not a theoretical problem.

Similar to the introduction of the `manylinux2010`platform, we will soon have the `manylinux2014` platform tag ([PEP-599](https://www.python.org/dev/peps/pep-0599/)). `manylinux2014` is supported since [pip 19.3|https://pip.pypa.io/en/stable/news/#id104]. To make use of this, I would have to upgrade to Python 3.8.

There are many new developments in the world of packaging, e.g. relating to PEP-517 and PEP-518. There can be packages without a `setup.py`, which again require a [newer version of pip](https://github.com/pypa/pip/pull/6606) to install.

Finally, `pip` also vendors many of its dependencies. These include `requests` and `certifi`. Both are security-relevant packages where I would prefer to have the ability to update.

Thanks for your time!

**Comment by robertofalk** [comment]
almost one year ago and not even comments on this.

**Comment by sophiewigmore** [comment]
@mhaas Apologies for the lack of response here, as mentioned in https://github.com/paketo-buildpacks/pip/issues/2, we focused a lot of efforts into making the

**Comment by sophiewigmore** [comment]
Hi there @mhaas, I sincerely apologize for the lack of response here. Is this something you are still interested in? As noted in https://github.com/paketo-buildpacks/pip/issues/2, our attention has been diverted to the Python CNB which is now officially supported. 

I think that you make a good point here about the use case, and might be willing to look into this if it's something that you're actively interested in. Let me know

**Comment by mhaas** [comment]
Hi @sophiewigmore, yes, this is absolutely something that I would like to see.

To state my current case:

* Newer pip has a much improved dependency resolution algorithm. I was just debugging an issue earlier with pip 20.1.1 (current default in the buildpack for Python 3.7) which simply does not exist in later pip versions.
* There is again a new Python standard related to packaging: [PEP-600](https://www.python.org/dev/peps/pep-0600/) which adds a new platform tag. The version of Pip currently in the Python 3.7 buildpack simply cannot install these. Support was added in [PIP 20.3](https://pip.pypa.io/en/stable/news/#v20-3).
** Case in point: Recent versions of psycopg2-binary ([2.9.*](https://pypi.org/project/psycopg2-binary/2.9.1/#files)) use the new platform tag. To install these, the maintainer recommends to [update pip](https://github.com/psycopg/psycopg2/issues/1317#issuecomment-873461240). Now imagine there is a security issue in a package that I need, but I cannot update because pip is too old.

So, having this would make my life much easier. Thanks, @sophiewigmore!

**Comment by sophiewigmore** [comment]
@mhaas Thank you for getting back to us! We can look into this, and I will keep you updated.
