### ISSUE TITLE
The default version should be updated to Python 3.

### ISSUE THREAD

**Issue by rvennam** [cloudfoundry/python-buildpack#19]
./bin/compile:DEFAULT_PYTHON_VERSION="python-2.7.9"

From the Python website: "Python 2.x is legacy, Python 3.x is the present and future of the language"

Are there plans to change the default python version (when none is specified in requirements.txt) to python 3?

**Comment by flavorjones** [comment]
Thank you for pointing this out! I've scheduled this work (see the referenced Tracker story above) and it will be updated in the next python-buildpack release.

Thanks for using Cloud Foundry!

**Comment by mcowger** [comment]
While I agree with the sentiment, that statement has been on the python site for *years*.

As it stands today, some important packages used in CF-deployed apps remain incompatible with Python 3, including:

* MySQL-python
* Fabric
* python-openid
* django-storages
* sqlachemy-migrate
* dateutils
* ipaddr
* Twisted

A more complete list can be found at http://py3readiness.org/

So while I'd like to see this too, I'd argue it breaks too many things to become the default at this time.

**Comment by rvennam** [comment]
Thanks for you comments - exactly what I was looking for. I'm happy to close this without updating.

**Comment by flavorjones** [comment]
@mcowger Thanks for your comments, we really do appreciate hearing from people who are more tightly connected to the Python community than we might be.

Can you help me understand what the threshold would be for Python 3 to become the default? That is, if not now, then when? Is the community as a whole not prioritizing Python 3 compatibility?

**Comment by mcowger** [comment]
I think the community as a whole *is* prioritizing Python 3, but there are some things that make that more difficult:

1. Some of the really important frameworks (like Twisted, Zope2, and MySQL-Python) aren't there.  Personally (and this is personal opinion), I think once those 3 are good, it could become the defaults.
2. So many of the popular tutorials out there (Learn Python The Hard Way, especially) and code snippets are Python 2 based that they carry some significant level of momentum with them (good or bad - its there).
3. For many coders, there's not enough new value in Python 3 (especially for new/intermediate coders) to justify making the changes needed to get 2.x code running in 3.x.


So, in my mind, I would want to see the above 3 modules become Py3 compatible, and I'd be willing to call it good.

I will also say i think there is an argument to be made (and I realize I am disagreeing with myself here) that perhaps CF could/should lead the way and just declare it the default anyways....

**Comment by flavorjones** [comment]
For now, closing this ticket because of the objections raised by @mcowger. I'm happy to open the conversation up again if the Pythonistas out there feel it's time to update the default.
