### ISSUE TITLE
HTTP request using python requests library is not using system/BOSH CA bundle

### ISSUE THREAD

**Issue by andreaslang** [cloudfoundry/python-buildpack#195]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "Pivotal Application Service",
   "build": "2.4.15-build.3",
   "support": "https://support.pivotal.io",
   "version": 0,
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.125.0",
   "osbapi_version": "2.14"
}
cf version 6.51.0+2acd15650.2020-04-07

What version of the buildpack you are using?
python_buildpack_1_7_11

If you were attempting to accomplish a task, what was it you were attempting to do?
Connecting to an https endpoint using the python requests library (pretty much the standard library on python for http requests) which uses custom trusted certificate added via https://docs.cloudfoundry.org/running/trusted-system-certificates.html

What did you expect to happen?
The call to succeed by using the configured certificates. 

What was the actual behavior?
The requests internal trust anchors are used causing an SSL error:
Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),)) 

A possible workaround is setting:
REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"

Would it be possible to have this documented and possibly a similar fix (auto setting it on application start) applied as there was for PIP_CERTS in https://github.com/cloudfoundry/python-buildpack/issues/100

To reproduce the error:
1. Add a custom certificate https://docs.cloudfoundry.org/running/trusted-system-certificates.html
2. Deploy basic python application with requests library as dependency
3. Make an https request to a website protected by the custom certificate 

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [x ] I have included steps for reproduction

**Comment by kvedurmu** [comment]
Hi @andreaslang. Thanks for reporting this! Your proposed workaround seems reasonable to me, we'll get this documented. This is also something that we should consider implementing in the next generation Paketo Buildpack, I'll file an issue there as well.

**Comment by kvedurmu** [comment]
This has been documented in [this commit](https://github.com/cloudfoundry/docs-buildpacks/commit/f2f48398c258103f887ba463b565a6618e3a7725) and the changes will be live under the [Python Buildpack docs](https://docs.cloudfoundry.org/buildpacks/python/index.html#bosh_trusted_cert)
