### ISSUE TITLE
ImportError: No module named 'encodings'

### ISSUE THREAD

**Issue by dlapiduz** [cloudfoundry/python-buildpack#20]
I am wondering if anyone else is seeing this same error...

On the `lucid` stack everything is working fine but if I switch to the new one `cflinuxfs2` I get this error when using Python.

Moreover the only runtime that even compiles is 3.4.2 since everything less than that requires libssl.0.9.8.

Did anyone get something like this?

**Comment by jtarchie** [comment]
@dlapiduz where are you running your apps?

Useful information would be:
* cf-release version
* the output of `cf buildpacks`

It sounds like you might be running into the issue, even though you switched stacks, you are using an older version of the buildpack that does not support the stack.

Thanks,

JT

**Comment by dlapiduz** [comment]
@jtarchie we have our own CF deployment. We are on the 206 release.

The output of of cf buildpacks is this but I am pushing with `-b https://github.com/cloudfoundry/python-buildpack`:

```
cf buildpacks
Getting buildpacks...

buildpack          position   enabled   locked   filename   
java_buildpack     1          true      false    java-buildpack-v2.7.1.zip   
ruby_buildpack     2          true      false    ruby_buildpack-cached-v1.3.0.zip   
nodejs_buildpack   3          true      false    nodejs_buildpack-cached-v1.2.1.zip   
go_buildpack       4          true      false    go_buildpack-cached-v1.2.0.zip   
python_buildpack   5          true      false    python_buildpack-cached-v1.2.0.zip   
php_buildpack      6          true      false    php_buildpack-offline-v3.1.0.zip   
```

Any ideas?

Thanks!

**Comment by jtarchie** [comment]
@dlapiduz, could you try deleting your application and restaging it? We suspect this might be due to cached binaries from the lucid64 stack, which are not getting appropriately removed.

Let us know if that works for you.

**Comment by dlapiduz** [comment]
@jtarchie I was definitely having issues with caching. This is happening on a fresh app.

Any other ideas?

**Comment by mhoran** [comment]
Hey @dlapiduz. There is a known issue with v206, Python, and cflinuxfs2. See the first point under runtime in the [release notes](https://github.com/cloudfoundry/cf-release/releases/tag/v207). You may want to try upgrading to v207 if possible. Otherwise, you may have to stick with the lucid stack.

**Comment by dlapiduz** [comment]
@mhoran I didn't realize this was a known issue. Thanks! Just upgraded to 207, will try again.
