### ISSUE TITLE
I am unable to login to django admin webpage after creating user.

### ISSUE THREAD

**Issue by praful-dhabekar** [cloudfoundry/python-buildpack#206]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "",
   "build": "",
   "support": "https://support.run.pivotal.io",
   "version": 0,
   "description": "Cloud Foundry sponsored by Pivotal",
   "authorization_endpoint": "https://login.run.pivotal.io",
   "token_endpoint": "https://uaa.run.pivotal.io",
   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
   "app_ssh_host_key_fingerprint": "e7:13:4e:32:ee:39:62:df:54:41:d7:f7:8b:b2:a7:6b",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
   "api_version": "2.152.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.run.pivotal.io/routing",
   "user": "0fa1ad78-2062-4d6c-b015-7818694a7154"
}
cf version 6.51.0+2acd15650.2020-04-07
```

I have a django app and I wrote one small script to create admin user. My script: 

```
echo "------ Create database tables ------"
python manage.py migrate --noinput

echo "------ create default admin user ------"
echo "from django.contrib.auth.modelsimport User; User.objects.create_superuser('admin', 'adminuser', 'Admin123')" | python manage.py shell

echo "------ starting gunicorn ------"
gunicorn wsgi:application

```
then I ran cf push `cf push -c "bash ./my_script.sh"`

After check logs I can see the command ran. But when I go to the url: `<my-app>/admin`, I am unable to login with credentials which I provided in the script.

So I ssh'd into app using` cf ssh <app-name>` and tried running this command: 
`echo "from django.contrib.auth.modelsimport User; User.objects.create_superuser('admin', 'adminuser', 'Admin123')" | python manage.py shell`

But I am getting following error: 
```
Traceback (most recent call last):
  File "manage.py", line 17, in <module>
    "Couldn't import Django. Are you sure it's installed and "
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
```
When I tried to check python version using `python --version` command then I got `Python 2.7.17`. Even though my runtime.txt have `python-3.6.11`

Can you please tell me how I can create admin user?

**Comment by sophiewigmore** [comment]
Hi @praful-dhabekar!
I'm having trouble reproducing this error, would you be able to provide an app for me to try this out with so I can try to help?

In terms of the python version issue, when you run `python --version` or `python3 --version` in the app container, you do not get the app python version, but the system python version instead. There is a binary in `/tmp/lifecycle/shell` that will invoke bash with the same environment as the app.

**Comment by menehune23** [comment]
@praful-dhabekar I'm closing this issue as stale. Please feel free to reopen if this is still a problem and you've narrowed it down to the buildpack itself. If you do so, please include a link to a minimal app repo that reproduces the problem you're seeing.
