### ISSUE TITLE
Need the latest fix of libbuildpack-dynatrace module in the python buildpack 

### ISSUE THREAD

**Issue by manitheja1** [cloudfoundry/python-buildpack#217]
Hi Team,
I could see the libbuildpack dynatrace module in the python buildpack is using 1.2.2 version. There has been a latest release(1.3.0) for the module which has a fix to customize oneagenturl(https://github.com/Dynatrace/libbuildpack-dynatrace/releases ).

We need that fix in the python buildpack. I know. could you please help us in getting the new release which will have the latest release of libbuildpack-dynatrace?

Thanks,
Manitheja

**Comment by kvedurmu** [comment]
This has been bumped and released in https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.7.22
