### ISSUE TITLE
buildpack

### ISSUE THREAD

**Issue by Rama0389** [cloudfoundry/python-buildpack#23]

**Comment by jtarchie** [comment]
@Rama0389. Do you have anything to add to this issue? I'm going to close it as it is empty, if you update it, let's reopen it.

**Comment by Rama0389** [comment]
Hi,

Sorry for the empty ticket.But My intention was to use sample Flask web application in IBM Bluemix and I ended up in error which “Build pack does not have the necessary files to detect application” and tired of troubleshooting.Could you please help me in resolving the buildpack error ?

I tried the ones :- heroku-pythoon buildpack,github/ephoning/python-buildpack etc…

Warm Regards,
Ramakrishnan
GB-FM | BT Radianz – OMS |Desk: +914442002700 Extn: 6614598,
Mobile: +91 9600235975 |Email : btgsgfsomssupport@virtusa.com

**Comment by jtarchie** [comment]
@Rama0389, we'll need a little more information about how you are deploying that application. This may not be a specific buildpack issue.

* How are you deploying the application? `cf push my-app`...
* What version of CF are you deploying to?

Thanks, JT

**Comment by Rama0389** [comment]
Archie,

Yes using  ….         cf push my-app

Version 6.12.0

Warm Regards,
Ramakrishnan
GB-FM | BT Radianz – OMS |Desk: +914442002700 Extn: 6614598,
Mobile: +91 9600235975 |Email : btgsgfsomssupport@virtusa.com

**Comment by jtarchie** [comment]
@Rama0389, we'll need more information than that.

* Do you have the output from `cf logs`?
* What version of the buildpacks `cf buildpacks` are on your cf deployment?
* What application code are you trying to push up?

Regards, JT

By the way, your email signature is appearing on the ticket on Github.

**Comment by Rama0389** [comment]
All I tried to do is run this example in my blue mix account ,

https://github.com/whitfiea/bluemix-python-flask-sample


I tried to pull the build pack from the github for eg. cf push <YOUR_APP_NAME> -m 128M -b https://github.com/cloudfoundry/python-buildpack

I don’t have the log with me right now..

Warm Regards,
Ramakrishnan
GB-FM | BT Radianz – OMS |Desk: +914442002700 Extn: 6614598,
Mobile: +91 9600235975 |Email : btgsgfsomssupport@virtusa.com

**Comment by jtarchie** [comment]
I think the issue that you might experiencing is that unsupported stack. The buildpack dropped support for lucid64 a couple of weeks ago because Ubuntu end of life that distro. If your deployment of cloud foundry support cflinuxfs2 try deploying your application on that stack.

To double check, run `cf stacks` and see that `cflinuxfs2` is listed, if it is, deploy your app with `cf push -s cflinuxfs2`.

**Comment by mcowger** [comment]
@jtarchie - blue mix is still using the lucid64 stack....

If you simply push without specifying the build pack, CF will generally guess and make a reasonable choice based on internally available buildpacks (`cf buildpacks` for a list).   I simply did a `cf push my-app` and it worked fine because Bluemix already have a python build pack installed.


```
mcowger@hex:~/Projects/t/bluemix-python-flask-sample (master)
$ cf push mcowger-flask -m 128M
Using manifest file /Users/mcowger/Projects/t/bluemix-python-flask-sample/manifest.yml

Updating app mcowger-flask in org matt@cowger.us / space dev as matt@cowger.us...
OK

Uploading mcowger-flask...
Uploading app files from: /Users/mcowger/Projects/t/bluemix-python-flask-sample
Uploading 16.3K, 7 files
Done uploading
OK

Stopping app mcowger-flask in org matt@cowger.us / space dev as matt@cowger.us...
OK

Starting app mcowger-flask in org matt@cowger.us / space dev as matt@cowger.us...
-----> Downloaded app package (8.0K)
-------> Buildpack version 1.3.1
-----> Installing runtime (python-2.7.9)
-----> Installing dependencies with pip
       You are using pip version 6.1.0.dev0, however version 7.1.0 is available.
       You should consider upgrading via the 'pip install --upgrade pip' command.
       Collecting Flask==0.10.1 (from -r requirements.txt (line 1))
         Downloading Flask-0.10.1.tar.gz (544kB)
       Collecting Werkzeug>=0.7 (from Flask==0.10.1->-r requirements.txt (line 1))
         Downloading Werkzeug-0.10.4-py2.py3-none-any.whl (293kB)
       Collecting Jinja2>=2.4 (from Flask==0.10.1->-r requirements.txt (line 1))
         Downloading Jinja2-2.7.3.tar.gz (378kB)
       Collecting itsdangerous>=0.21 (from Flask==0.10.1->-r requirements.txt (line 1))
         Downloading itsdangerous-0.24.tar.gz (46kB)
       Collecting markupsafe (from Jinja2>=2.4->Flask==0.10.1->-r requirements.txt (line 1))
         Downloading MarkupSafe-0.23.tar.gz
       Installing collected packages: markupsafe, itsdangerous, Jinja2, Werkzeug, Flask
         Running setup.py install for markupsafe
         Running setup.py install for itsdangerous
         Running setup.py install for Jinja2
         Running setup.py install for Flask
       Successfully installed Flask-0.10.1 Jinja2-2.7.3 Werkzeug-0.10.4 itsdangerous-0.24 markupsafe-0.23
You are using pip version 6.1.0.dev0, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
-----> Uploading droplet (33M)

0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App mcowger-flask was started using this command `python welcome.py`

Showing health and status for app mcowger-flask in org matt@cowger.us / space dev as matt@cowger.us...
OK

requested state: started
instances: 1/1
usage: 128M x 1 instances
urls: mcowger-flask.mybluemix.net
last uploaded: Tue Jul 7 23:03:27 UTC 2015
stack: lucid64

     state     since                    cpu    memory          disk           details
#0   running   2015-07-07 04:04:44 PM   0.0%   51.7M of 128M   118.7M of 1G
```
