### ISSUE TITLE
Option to enable shared library support

### ISSUE THREAD

**Issue by chrismasonthom-co** [cloudfoundry/python-buildpack#239]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
`cf.exe version 7.1.0+4c3168f9a.2020-09-09`

**What version of the buildpack you are using?**
`v1.7.26`

**If you were attempting to accomplish a task, what was it you were attempting to do?**
I'm trying to use the `reticulate` R package to bind to python (multi-buildpack app deployment), so that I can render an Rmarkdown document containing both R and python code chunks.

**What did you expect to happen?**
Successful installation of python and dependencies in requirements.txt, and successful discovery and binding from reticulate. From reticulate's [docs](https://rstudio.github.io/reticulate/articles/versions.html#locating-python):
> Note that for reticulate to bind to a version of Python it must be compiled with shared library support (i.e. with the --enable-shared flag).

**What was the actual behavior?**
Successful installation of all the software, but reticulate failed to bind with error: `Python shared library not found, Python bindings not loaded`. Which suggests that the python buildpack was not compiled with `--enable-shared`.

This is not a bug report, I don't think anything isn't working as intended - I just would like to know if it's possible to provide a version of the python buildpack compiled with `--enable-shared` ? The changelog (admittedly from 6 years ago) suggests that this used to be provided, with runtimes such as `python-2.7.8-shared` (as in [this issue](https://github.com/cloudfoundry/python-buildpack/issues/7))

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by menehune23** [comment]
@chrismasonthom-co, thanks for posting and apologies for the late response. Most new feature development is focused on the [Paketo Python buildpack](https://github.com/paketo-buildpacks/python), so you may want to post an issue there, while trying out that buildpack in your workflow.

I'll close this issue, but here are some options if you'd like to stick with this buildpack:
- Fork this buildpack to add the desired runtime
- Reopen and continue the conversation if this is still an issue
