### ISSUE TITLE
ERR You are using pip version 6.1.0.dev0, however version 7.1.0 is available.

### ISSUE THREAD

**Issue by cclauss** [cloudfoundry/python-buildpack#24]
The upgrade to the current version of pip should be pulled from [upstream](https://github.com/heroku/heroku-buildpack-python).

**Comment by aemengo** [comment]
@cclauss We've already pulled the changes from upstream. However, the change currently resides on our 'develop' branch. You can see the commit here: https://github.com/cloudfoundry/python-buildpack/commit/73596c129210068b4dc9f5eb4259baa611646e54. We will officially pull this soon when we cut a release of the python buildpack. 

Many thanks for the update!

**Comment by flavorjones** [comment]
This was released in python-buildpack v1.5.0: https://github.com/cloudfoundry/python-buildpack/releases/tag/v1.5.0
