### ISSUE TITLE
WARNING: Requirement looks like a filename, but the file does not exist

### ISSUE THREAD

**Issue by igormcsouza** [cloudfoundry/python-buildpack#243]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**
```
{
   "name": "VMware Tanzu Application Service",
   "build": "2.9.8-build.6",
   "version": 0,
   "token_endpoint": "https://uaa.sr1.pcf.dell.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.145.0",
   "osbapi_version": "2.15",
}
cf.exe version 6.53.0+8e2b70a4a.2020-10-01
```

**What version of the buildpack you are using?** I'm using dicf_python_buildpack_1716_cflinuxfs3

**If you were attempting to accomplish a task, what was it you were attempting to do?** I want to push the code I have to the cloud foundry and run it as a flask restapi.

**What did you expect to happen?** I want to install my local package, which is delivered on the root of the code as lib/<package-name>.whl

**What was the actual behavior?** It crashes because it didn't find the package causing the push to fail.

I'm using poetry to create the requirements.txt using, with the command `poetry export`.
Then, I push the code using cf cli, which builds the application on the cloud foundry
But then during the process I get the following

```
...
-----> Running Pip Install
          adding trusted host: 'dcsartifacts.dell.com' (from line 2 of /tmp/app/requirements.txt)
          Ignoring atomicwrites: markers 'python_version >= "2.7" and python_full_version < "3.0.0" and sys_platform == "win32" or python_full_version >= "3.4.0" and sys_platform == "win32"' don't match your environment
          Ignoring colorama: markers 'python_version >= "2.7" and python_full_version < "3.0.0" and sys_platform == "win32" or python_full_version >= "3.5.0" and sys_platform == "win32"' don't
match your environment
          WARNING: Requirement 'tfsapigateway @ file:///C:/Users/Igor_Chagas/Documents/tfs/tfsmetrics-backend/backend/libs/tfsApiGateway-0.5.3-py3-none-any.whl' looks like a filename, but the file does not exist
...
Processing ./tfsapigateway @ file:/C:/Users/Igor_Chagas/Documents/tfs/tfsmetrics-backend/backend/libs/tfsApiGateway-0.5.3-py3-none-any.whl
          ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/tmp/app/tfsapigateway @ file:/C:/Users/Igor_Chagas/Documents/tfs/tfsmetrics-backend/backend/libs/tfsApiGateway-0.5.3-py3-none-any.whl'
```

I know the current path will not be find, because is my absolute path, but I have no Idea where it is then!! I tryed on /tmp/app... But it looks like it goes somewhere I just can't find. It there any one that know where exacly I have to point this package so it can be found? There is another way to build this using poetry directly instead of having to create this requirements?

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by arjun024** [comment]
Not familiar with poetry, can you include a sample app/your generated `requirements.txt` so that we can take a look?

**Comment by menehune23** [comment]
@igormcsouza Are you still having issues with this? The issue looks to be with your generated requirements, as your logs reference a local directory `file:///C:/Users/Igor_Chagas/`.

I'm going to close this for now, but if you find that there is still some issue with the buildpack, feel free to reopen. If you do so, be sure to include a link to a minimal repo that reproduces the issue, along with any other reproduction steps.
