### ISSUE TITLE
collectstatic is not being run when using Pipfile instead of requirements.txt

### ISSUE THREAD

**Issue by TYsewyn** [cloudfoundry/python-buildpack#245]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
```
{
   "name": "VMware Tanzu Application Service",
   "build": "2.10.10-build.24",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/2-10/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.[masked]",
   "token_endpoint": "https://uaa.[masked]",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "ssh.[masked]:2222",
   "app_ssh_host_key_fingerprint": "e9:7e:30:8b:93:aa:f8:2c:6e:9f:bc:28:a7:68:47:e3",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.[masked]:443",
   "api_version": "2.150.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.[masked]/routing",
   "user": "ed743cc4-7dc2-4f4e-85fe-7a44e21c44d2"
}
```
and
`cf version 7.2.0+be4a5ce2b.2020-12-10`

What version of the buildpack are you using?
`1.7.26`

If you were attempting to accomplish a task, what was it you were attempting to do?
`cf push` using the bare minimum `manifest.yaml` definition, using a `Pipfile` and `Pipfile.lock` where Django was added as a dependency.

What did you expect to happen?
Expected to see `Running python manage.py collectstatic --noinput --traceback` or `x static files copied to '/tmp/app/staticfiles', y unmodified, z post-processed.` in the logs.

What was the actual behavior?
```
   -----> Python Buildpack version 1.7.26
   -----> Supplying Python
   -----> Installing python 3.8.6
          Copy [/tmp/buildpacks/10c7e1503eb973373fa2544eacb7de1c/dependencies/8bae547a8d95591ac98540eee72e3bc8/python_3.8.6_linux_x64_cflinuxfs3_8b697568.tgz]
   -----> Installing pip-pop 0.1.5
          Copy [/tmp/buildpacks/10c7e1503eb973373fa2544eacb7de1c/dependencies/2e88c958cb5cf0638aa875fa2e7b99e0/pip-pop-0.1.5-b32efe86.tar.gz]
          Generating 'requirements.txt' from Pipfile.lock
   -----> Running Pip Install
          [omitted]
          Successfully installed ...
   Exit status 0
```

I suspect that the `requirements.txt` file is being generated in the `/tmp` directory rather than the build directory. In turn, the `HandleCollectstatic` function in `finalize.go` is being [stopped prematurely](https://github.com/cloudfoundry/python-buildpack/blob/master/src/python/finalize/finalize.go#L71) because it can't find the file in the build directory.

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [x] I have included steps for reproduction

**Comment by TYsewyn** [comment]
I just went over the script again and found out that it's not because it's being written to the `/tmp` directory.
The `requirements.txt` file is being written correctly to the build dir, but it's because of [this statement](https://github.com/cloudfoundry/python-buildpack/blob/master/src/python/supply/supply.go#L169) that it's not being picked up in the finalize stage.

**Comment by arjun024** [comment]
We'll look into this. Meanwhile could you provide a simple app we can reproduce the issue with? Something like [this](https://github.com/cloudfoundry/python-buildpack/tree/master/fixtures/django_web_app) but using Pipfile{,.lock}.

**Comment by TYsewyn** [comment]
Definitely! I'll create a PR with a sample app ASAP.

**Comment by TYsewyn** [comment]
@arjun024 Would it be possible to look at the PR and comment/adjust where necessary to get this fix shipped with the upcoming release? Thanks!

**Comment by arjun024** [comment]
@TYsewyn Will review it in a couple of days. Thanks.

**Comment by menehune23** [comment]
@TYsewyn I looked at the PR and it looks to be pretty much complete. I'm seeing if I can get a buildpack maintainer to sign off on it and merge it.

**Comment by menehune23** [comment]
Closing this and associated PR #246 as stale. Feel free to reopen if needed.
