### ISSUE TITLE
Issues/questions about GDAL dependency

### ISSUE THREAD

**Issue by jghiloni** [cloudfoundry/python-buildpack#25]
I'm trying to tweak the buildpack code so it will vendor GDAL along with libffi and libmemcache, but some things are kind of confusing to me:

* When I try to download `https://lang-python.s3.amazonaws.com/cflinuxfs2/libraries/vendor/gdal.tar.gz` to get the checksum to add to `manifest.yml`, I get a 403. 
* What is the difference between `bin/steps/gdal` and `builds/libraries/vendor/gdal`? It seems like neither use vendored dependencies, which I'm trying to fix, but the `libffi` and `libmemcache` counterparts in `builds/libraries/vendor` also never used vendored dependencies. I cannot seem to figure out when the `builds/libraries/vendor/*` scripts are even called. Is this something I need to watch for?

**Comment by flavorjones** [comment]
Hi @jghiloni - thanks for asking these questions!

You're trying to download `gdal.tar.gz` using the `CF_STACK` value, which is `cflinuxfs2`. However, the binary in question was compiled for Heroku stacks, so you'll need to use `cedar` or `cedar-14` for that value:

```
gdal $ wget https://lang-python.s3.amazonaws.com/cedar-14/libraries/vendor/gdal.tar.gz
--2015-09-15 14:07:56--  https://lang-python.s3.amazonaws.com/cedar-14/libraries/vendor/gdal.tar.gz
Resolving lang-python.s3.amazonaws.com (lang-python.s3.amazonaws.com)... 54.231.66.9
Connecting to lang-python.s3.amazonaws.com (lang-python.s3.amazonaws.com)|54.231.66.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55632483 (53M) [application/octet-stream]
Saving to: ‘gdal.tar.gz’

100%[==============================================================================================================================>] 55,632,483  13.4MB/s   in 6.0s   

2015-09-15 14:08:03 (8.89 MB/s) - ‘gdal.tar.gz’ saved [55632483/55632483]

```

The scripts you're asking about are inherited from our upstream legacy, the Heroku buildpack.

`bin/steps/gdal` is run at staging time, and will try to detect a declared dependency on GDAL and install the appropriate binary from the appropriate S3 path.

`builds/libraries/vendor/gdal` is a tool that's used to compile gdal for a specific stack. The binary you might download from S3 was presumably built using this tool.

If you look at https://github.com/cloudfoundry/python-buildpack/blob/master/bin/steps/gdal#L25 you should try vendoring gdal into a local directory in your app named (gulp) `.heroku/vendor`. Specifically, the file `.heroku/vendor/bin/gdalserver` should exist, which will happen if you untar `gdal.tar.gz` in the `.heroku/vendor` directory.

Does this help?

**Comment by jghiloni** [comment]
I think it does help. What you're saying is that the tgz file that is referenced in `build/…` basically outputs the contents of the tgz file that is referenced in `bin/steps/gdal`?

And is there a 1 – 1 mapping between heroku and CF stacks? That is, if I'm only building for `cflinuxfs2` should I choose `cedar-14` over `cedar`?

From: Mike Dalessio
Reply-To: cloudfoundry/python-buildpack
Date: Tuesday, September 15, 2015 at 12:14
To: cloudfoundry/python-buildpack
Cc: Josh Ghiloni
Subject: Re: [python-buildpack] Issues/questions about GDAL dependency (#25)


Hi @jghiloni<https://github.com/jghiloni> - thanks for asking these questions!

You're trying to download gdal.tar.gz using the CF_STACK value, which is cflinuxfs2. However, the binary in question was compiled for Heroku stacks, so you'll need to use cedar or cedar-14 for that value:

gdal $ wget https://lang-python.s3.amazonaws.com/cedar-14/libraries/vendor/gdal.tar.gz
--2015-09-15 14:07:56--  https://lang-python.s3.amazonaws.com/cedar-14/libraries/vendor/gdal.tar.gz
Resolving lang-python.s3.amazonaws.com (lang-python.s3.amazonaws.com)... 54.231.66.9
Connecting to lang-python.s3.amazonaws.com (lang-python.s3.amazonaws.com)|54.231.66.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 55632483 (53M) [application/octet-stream]
Saving to: ‘gdal.tar.gz’

100%[==============================================================================================================================>] 55,632,483  13.4MB/s   in 6.0s

2015-09-15 14:08:03 (8.89 MB/s) - ‘gdal.tar.gz’ saved [55632483/55632483]



The scripts you're asking about are inherited from our upstream legacy, the Heroku buildpack.

bin/steps/gdal is run at staging time, and will try to detect a declared dependency on GDAL and install the appropriate binary from the appropriate S3 path.

builds/libraries/vendor/gdal is a tool that's used to compile gdal for a specific stack. The binary you might download from S3 was presumably built using this tool.

If you look at https://github.com/cloudfoundry/python-buildpack/blob/master/bin/steps/gdal#L25 you should try vendoring gdal into a local directory in your app named (gulp) .heroku/vendor. Specifically, the file .heroku/vendor/bin/gdalserver should exist, which will happen if you untar gdal.tar.gz in the .heroku/vendor directory.

Does this help?

**Comment by flavorjones** [comment]
@jghiloni -- Apologies for not responding earlier.

There's not necessarily a 1-to-1 correspondence between Heroku and CF stacks; but it so happens that `cedar-14` and `cflinuxfs2` are roughly equivalent, in that they're both derived from Ubuntu 14.04.

CF's equivalent stack for `cedar` was `lucid64`, which we stopped supporting when Canonical stopped supporting Lucid (Ubuntu 10.04) on 2015-04-29.

The announcement for CF ending support for lucid64 is here:

> https://groups.google.com/a/cloudfoundry.org/forum/#!msg/vcap-dev/gU7rpD8MSC4/9VfzwhUx_CsJ
