### ISSUE TITLE
No way to specify a non-default miniconda version to be used with my app

### ISSUE THREAD

**Issue by arjun024** [cloudfoundry/python-buildpack#259]
What version of the buildpack you are using?
v1.7.30

If you were attempting to accomplish a task, what was it you were attempting to do?
Use miniconda38

What did you expect to happen?
Have a way to specify the version

What was the actual behavior?
Couldn't find a way to specify non-default version

It looks like miniconda37 and miniconda38 are packaged with the buildpack (https://github.com/cloudfoundry/python-buildpack/blob/v1.7.30/manifest.yml#L44-L67) but seems to be installing the default version always (https://github.com/cloudfoundry/python-buildpack/blob/v1.7.30/src/python/conda/conda.go#L85)

**Comment by menehune23** [comment]
Hey @arjun024, is this still an issue that needs addressing in this buildpack? (vs the newer [Paketo buildpack](https://github.com/paketo-buildpacks/python)). I'll close this as it's a few months old, but feel free to reopen if necessary.
