### ISSUE TITLE
libpython incompatible to python binary?

### ISSUE THREAD

**Issue by butla** [cloudfoundry/python-buildpack#27]
**The gist:**
I'm looking at python_buildpack-cached-v1.5.1.zip, specifically dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_python_python-2.7.9-linux-x64.tgz

lib/libpython2.7.so.1.0 is built for 2-byte unicode characters (checked with nm libpython2.7.so.1.0 | grep Unicode), while bin/python2.7 is built for 4-byte unicode (checked with import sys; sys.maxunicode > 65535). I'm not an expert on C extensions or buildpacks, but doesn't this mean that C extensions using lipython won't work with the provided Python?

**More context:**
I was trying to push an app that's using PySide. The configuration of the machine it's wheel is built on should be similar to cflinuxfs2. I've put the wheel in vendor along with other dependencies, set LD_LIBRARY_PATH so that the code will see PySide's native libraries.

But then this happens:
```ImportError: /app/.heroku/python/lib/python2.7/site-packages/PySide/QtCore.so: undefined symbol: PyUnicodeUCS4_FromWideChar```

As I understand, this should be provided by libpython, but the current one has 2-byte unicode chars, so you have functions like this PyUnicodeUCS**2**_FromWideChar

**Comment by jtarchie** [comment]
@butla, I believe if the c extensions doesn't use any of those functions (`PyUnicodeUCS4_FromWideChar`) it will work against our version of `libpython`.

That being said, we need to look to see if this is a configurable thing, and if so, if it is standard practice to use 2-byte or 4-byte unicode in Python.

Are you able to recompile again a 2-byte version of `libpython`?

**Comment by jtarchie** [comment]
It looks like 2-byte is the default setting (via `./configure`).

```
 --enable-unicode[=ucs[24]]
                          Enable Unicode strings (default is ucs2)
```

What Python are you compiling against? Via `apt-get`?

**Comment by butla** [comment]
@jtarchie yeah, the extensions that don't use unicode will work, but others won't be as lucky. The 2-byte is the default one, but Ubuntu and the like use the 4-byte setting. cflinuxfs2 seems to be descendant from Ubuntu stack... (at least that's the feeling I got from looking at the Docker image https://github.com/cloudfoundry/stacks/blob/master/cflinuxfs2/Dockerfile) And, like I've said, the Python binary is built with 4-byte unicode, so there seems to be a discrepancy there.

I don't know if this will stop PySide from working when I finally build it against 2-byte unicode libpython, as I'm no CMake wizard, but I'll try to get this to work on Monday. Then I'll have some more info.

**Comment by jtarchie** [comment]
@butla, what was the result of the recompiling?

When we build Python, we just use the standard configuration. The Python provided on the *cflinuxfs2* (via `apt-get`) is not the Python used with the buildpack and app. We have to compile and distribute [multiple versions](https://github.com/cloudfoundry/python-buildpack/blob/master/manifest.yml#L29-L69).

**Comment by butla** [comment]
@jtarchie You're right, I'm closing the issue. Though I haven't manage to compile PySide yet, because of other tasks with higher priority.

Although I think I'm close, having essentially built my own distro (based on Debian Jessie Docker image) with a 2-byte Python. I still need to recompile Python once again with zlib to get Pip.
