### ISSUE TITLE
Unable to install a dependency(fbprophet) in cf through conda

### ISSUE THREAD

**Issue by rakeshn1** [cloudfoundry/python-buildpack#309]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "IBM Cloud",
   "build": "v16.11.0",
   "support": "http://ibm.biz/bluemix-supportinfo",
   "version": 0,
   "description": "IBM Bluemix",
   "authorization_endpoint": "https://iam.cloud.ibm.com/cloudfoundry/login/us-south",
   "token_endpoint": "https://uaa.us-south.cf.cloud.ibm.com",
   "min_cli_version": null,
   "min_recommended_cli_version": null,
   "app_ssh_endpoint": "ssh.us-south.cf.cloud.ibm.com:2222",
   "app_ssh_host_key_fingerprint": "c7:1f:89:2a:62:3b:78:a9:08:c9:33:81:fb:39:26:da",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.us-south.cf.cloud.ibm.com:443",
   "api_version": "2.164.0",
   "osbapi_version": "2.15",
   "user": "3f744d97-649b-49aa-acde-f6ad0bef4754"
}

cf version 6.53.0+8e2b70a4a.2020-10-01

What version of the buildpack you are using?
Python Buildpack version 1.7.37

If you were attempting to accomplish a task, what was it you were attempting to do?
I'm trying to push a python flask app into cf. Locally, all the dependencies are installed through conda in a conda enviroment. So, I configured environment.yml file with required dependencies for the app and pushed it to cf.

What did you expect to happen?
I expected that all dependencies will be downloaded through conda environment and app starts running in cf.

What was the actual behavior?
On pushing the app into cf, one of package is not getting installed on cf due to which deployment is failing and app is not started. The package which is not getting installed is 'fbprophet'. I'm able to install this package locally with conda, but in cf it is failing.
![image](https://user-images.githubusercontent.com/78629375/117052763-f6de4600-accc-11eb-8a15-6dc516b48bd6.png)

Steps to reproduce:

Below is requirements.txt file
![image](https://user-images.githubusercontent.com/78629375/117053453-d5318e80-accd-11eb-955d-f90ae6ab3c2b.png)

 and  environment.yml
![image](https://user-images.githubusercontent.com/78629375/117053172-7e2bb980-accd-11eb-98d9-f6ab673ddb94.png)

With this I have written an app.py file  and I tried pushing into cf using ` ibmcloud cf push python-app -c "python app.py" `

Please confirm where necessary:
* [ yes ] I have included a log output
* [ yes ] My log includes an error message
* [ yes ] I have included steps for reproduction

**Comment by arjun024** [comment]
It looks like `fbprophet` is not a standard conda package, and rather present in `conda-forge`. See https://anaconda.org/conda-forge/fbprophet
You should be able set the conda-forge channel in your `enviroment.yml` as follows to get it installed:
```
channels:
  - conda-forge
 ```
