### ISSUE TITLE
Can't deploy python application to offline buildpack

### ISSUE THREAD

**Issue by amaltson** [cloudfoundry/python-buildpack#32]
I'm trying to deploy a Python application using the latest 1.5.4 cached buildpack. I get the following error:

```
...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (441.8K)
Downloading buildpacks (python-offline)...
Downloading python-offline...
Downloaded python-offline
Downloaded buildpacks
Staging...
/tmp/buildpacks/716b4c887fc391b63f824f71998ae460/bin/compile: line 22: /tmp/buildpacks/716b4c887fc391b63f824f71998ae460/compile-extensions/bin/check_stack_support: No such file or directory
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
BuildpackCompileFailed
```

The `--recent` logs show the same exception as above.

**Comment by jtarchie** [comment]
@amaltson, did you build the buildpack yourself? If so, when you checked out the repo, it looks like you didn't run `git submodule update --init`. These are [instructions](https://github.com/cloudfoundry/python-buildpack#building) to building your own buildpack.

We do create pre-packed buildpacks in [Github Releases](https://github.com/cloudfoundry/python-buildpack/releases), too.

**Comment by amaltson** [comment]
@jtarchie ... I completely forgot to do the `git submodule update --init`. Very sorry about that!

Didn't know you had GitHub Releases, that's awesome! I'll just use that.
