### ISSUE TITLE
Failed compiling app with scipy requirement

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/python-buildpack#35]
I'm trying this right now (on Pivotal Web Services) and it's failing to compile:

`$ cf push test-pandas -b python_buildpack -c 'python server.py' --random-route | tee /tmp/test-pandas-cf.log`

 Here's my `requirements.txt` (identical to https://github.com/cloudfoundry/python-buildpack/issues/22):

```
Flask==0.10.1
itsdangerous==0.24
Jinja2==2.7.3
MarkupSafe==0.23
nltk==3.0.2
numpy==1.9.2
pandas==0.16.1
python-dateutil==2.4.2
pytz==2015.4
scikit-learn==0.16.1
scipy==0.15.1
six==1.9.0
Werkzeug==0.10.4
```

Here's my `server.py` (though it should be irrelevant for failed staging):

```
from flask import Flask
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

app = Flask(__name__)

@app.route("/")
def hello():
    return "Hello World!"

if __name__ == "__main__":
    app.run()
```

Those are the only two files in my project's directory.

Here is the log output: https://gist.github.com/Amit-PivotalLabs/179dc16bc363893f4e79

The error message seems to be saying there's no Fortran compiler found.  `cflinuxfs2` indeed appears to have no Fortran compiler, just `[libgfortran3](https://www.opencsw.org/package/libgfortran3/)`.

Ignoring `server.py`, my overall goal is to leverage the v3 CC API to parallelize a bunch of one-off tasks (ETL + some basic machine learning).

**Comment by flavorjones** [comment]
SciPy support requires , as you discovered,  Fortran compiler.

We have multiple threads going with customers, OSS users, and Data Science to determine whether we want to support this and if so, how to do it without unreasonably increasing the size of the rootfs.

**Comment by fanyang-ceg** [comment]
Is there a way to package gfortran with SciPy?

**Comment by Amit-PivotalLabs** [comment]
I made a docker image with python2.7 and scipy which I can use on CF for my
needs.  If it's of use to anyone, here it is:
https://hub.docker.com/r/amitkgupta/python-2.7-machine-learning/

**Comment by fanyang-ceg** [comment]
Do you have any guide of how to push the image to CF? I’m a new to the environment.

Thanks,

Fan

**Comment by Amit-PivotalLabs** [comment]
You can use this as a base image for your own application, by creating an image that starts `FROM` this image and then `COPY`s (or `ADD`s) in your app's code.  You could also just play around with this:

```
cf push ml-workspace --docker-image amitkgupta/python-2.7-machine-learning --health-check-type none --no-route
cf ssh ml-workspace
```

**Comment by jvshahid** [comment]
Closing this issue since we are researching possible solutions to making it possible for data scientists to push their apps to CF. Scipy is definitely a required dependency for data scientists.

**Comment by mridhuljp** [comment]
Started hitting the same problem while using pandas lib on python buildpack and cflinuxfs2 stack.
