### ISSUE TITLE
Please consider upgrading the version of `pip` in the buildpack

### ISSUE THREAD

**Issue by flavorjones** [cloudfoundry/python-buildpack#36]
Currently, I see this message when I push:

```
You are using pip version 7.1.2, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

See https://pip.pypa.io/en/stable/news/ for more information on release cadence and backwards-incompatibilities.

**Comment by jtarchie** [comment]
It looks like the [upstream changes from Heroku](https://github.com/heroku/heroku-buildpack-python/blob/master/vendor/pip-8.1.0.tar.gz) will provide that upgrade. We have it scheduled for Monday to pull down the latest changes.

**Comment by Dannyzen** [comment]
Hi @flavorjones this has been completed on https://github.com/cloudfoundry/python-buildpack/commit/bece4fd6f12fb9e7488ac0bd6649501db89f2340 and is available in the develop branch.
