### ISSUE TITLE
Support For Appdynamics

### ISSUE THREAD

**Issue by pkumar-appd** [cloudfoundry/python-buildpack#37]
Hi,

I am working on Python Buildpack for Appdynamics.
While adding support It seems that we need to run command "pyagent run"  with appdynamics controller details. But command is failing

Can you please provide details on how to go ahead with support for appdynamics.

**Comment by jvshahid** [comment]
Hi @pkumar-appd, `command is failing` isn't actionable. without more details there ins't much we can do. can you provide more details, e.g. the command you are trying to run and the error output that you are getting.

**Comment by pkumar-appd** [comment]
Hi @jvshahid Following are the commands i am running from the buildpack. 

pip install virtualenv
virtualenv env
env/bin/pip install --pre appdynamics

Locally i am able to download appdynamics modules using same command.
But want them to be downloaded from buildpack.

**Comment by cclauss** [comment]
I would avoid installing a virtualenv...  this machine is dedicated to you so virtualenv does not really help.

Put `appdynamics`into `requirements.txt` and then put `pyagent run` into `Procfile`???

**Comment by ForestEckhardt** [comment]
@cclauss is this a confirmed solution to the problem at hand? Would love to know!

**Comment by pkumar-appd** [comment]
@cclauss Sure, 
I have removed support of virtual env. Appdynamics is also added to requirements.txt.
But to have python application monitored, there is a need to specifically start pyagent proxy in background.
Correct me if i am wrong, is it fine to add following commands in Procfile.
pyagent proxy start -c appdynamics.config -d
pyagent run 

appdynamics.config contains connection details that leads to application monitoring on appdynamics controller.

**Comment by geramirez** [comment]
Thanks we'll leave this up for future reference, @pkumar-appd and @cclauss

**Comment by jchesterpivotal** [comment]
Hi all,

As there are no more actions for the buildpacks team to take, we are going to close this issue.
