### ISSUE TITLE
Upgrade pip

### ISSUE THREAD

**Issue by pivotal-studionow** [cloudfoundry/python-buildpack#38]
I see the following output in my deploys:
```
ERR You are using pip version 7.1.2, however version 8.1.1 is available.
2016-03-17T11:23:27.02-0700 [STG/0]      
ERR You should consider upgrading via the 'pip install --upgrade pip' command.
```
Could we upgrade the version of pip used by the buildpack?

**Comment by RochesterinNYC** [comment]
Hi, the version of `pip` has been updated by [upstream changes](https://github.com/cloudfoundry/python-buildpack/commit/bece4fd6f12fb9e7488ac0bd6649501db89f2340) from Heroku that have been merged into [develop](https://github.com/cloudfoundry/python-buildpack/commits/develop).

It will be made available in the next release of the python buildpack.
