### ISSUE TITLE
Running heroku config:set DISABLE_COLLECTSTATIC=1

### ISSUE THREAD

**Issue by derekalvarado** [cloudfoundry/python-buildpack#44]
Where is one supposed to put this command?

`heroku config:set DISABLE_COLLECTSTATIC=1`

**Comment by RochesterinNYC** [comment]
@derekalvarado What are you trying to do with that command?

These buildpacks are intended to run on Cloud Foundry, not Heroku.

**Comment by derekalvarado** [comment]
The build fails because I haven't set STATIC_FILES in my settings.py. My service isn't serving any static files, and per the error output (from the cf cli), I should use `heroku config:set DISABLE_COLLECTSTATIC=1`, but I don't where exactly that is supposed to go.

**Comment by derekalvarado** [comment]
Actually, I found this little gem in bin/steps/collectstatic

`[ -f .heroku/collectstatic_disabled ] && DISABLE_COLLECTSTATIC=1`

Looks like I could either make a .heroku/collectstatic_disabled file (which I did, and works) or put DISABLE_COLLECTSTATIC=1 in the manifest.yml (which I haven't tried yet, but probably works)

**Comment by ChauhanSiddharth** [comment]
> Where is one supposed to put this command?
> 
> `heroku config:set DISABLE_COLLECTSTATIC=1`

in Heroku CLI : https://devcenter.heroku.com/articles/heroku-cli#download-and-install

**Comment by prezine** [comment]
it's not something you add, you can launch your terminal and run ```heroku apps``` after a successful ```heroku login``` then ```heroku config:set DISABLE_COLLECTSTATIC=1 --app <name of app>``` that's all.

**Comment by SwingsNFI** [comment]
Hey, im beginner, so what's happening if i run that command `heroku config:set DISABLE_COLLECTSTATIC=1` ?
