### ISSUE TITLE
Question Buildpack

### ISSUE THREAD

**Issue by ChrisDelClea** [cloudfoundry/python-buildpack#449]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

What version of the buildpack you are using?

If you were attempting to accomplish a task, what was it you were attempting to do?

I want to install dependencies from both, pypi and with mini conda.

What did you expect to happen?

That i can use both by defining a manifest.yml, requirements.txt and environment.yml .
First, the dependencies from the environment.yml are used, afterwards the missing 
dependencies ( that are not available on conda) are installed from pypi.

What was the actual behavior?

Only dependencies from enviromental.yml are installed.

Please confirm where necessary:
* [x] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

In addition, by installing dependencies from conda, i get the following: 

![image](https://user-images.githubusercontent.com/19912393/148034754-c842ff61-5a5d-46ec-8256-a7fbd3608ada.png)

Is there a way to invoke yes? I actually do not have controll over the terminal so i guess
it would have to be specified in advance. But could not find anything similar in the docu or on google. 

Best regards
Chris

**Comment by brayanhenao** [comment]
@ChrisDelClea Could you please provide the example application you used in order to reproduce the error?

**Comment by ryanmoran** [comment]
Closing. Feel free to re-open with more details.
