### ISSUE TITLE
Regarding Adding extension file to buildpack for Appdynamics

### ISSUE THREAD

**Issue by pkumar-appd** [cloudfoundry/python-buildpack#46]
Hi,

I am trying to add an extension file in the buildpack. The purpose of this file is to initialize Appdynamics agent specific environment variables by reading VCAP_APPLICATION and VCAP_SERVICES.
At what location in buildpack shall i add this file. Also any inputs on from where the call needs to be made to this extension file.

**Comment by RochesterinNYC** [comment]
@pkumar-appd a logical place for something like this might be as a script in the `bin/steps` directory: https://github.com/cloudfoundry/python-buildpack/tree/develop/bin/steps

We have a few other scripts in there to install or setup specific libraries.

**Comment by pkumar-appd** [comment]
@RochesterinNYC Correct i have been referring to scripts under that directory.
Is it good practice to call this new extension script directly from pip-install.

**Comment by RochesterinNYC** [comment]
I'm not sure what you mean by "directly from pip-install"?

Our setup scripts for the other dependencies run like so:

https://github.com/cloudfoundry/python-buildpack/blob/master/bin/compile#L218-L243

**Comment by pkumar-appd** [comment]
Thanks @RochesterinNYC I am able to create a new extension file and set appdynamics specific variables using VCAP_SERVICES and VCAP_APPLICATION.
Facing an issue, I need to set an environment variable and use it under my application. Looks like when i export a variable under that script it is not visible in my application. I need to access that environment variable from a python script. For example: Setting APPD_CONTROLLER_HOST in the extension script that is part of buildpack. And accessing APPD_CONTROLLER_HOST  from python file using os.environ['APPD_CONTROLLER_HOST'] but its not returning any value.

**Comment by RochesterinNYC** [comment]
Environment variables set in the staging container do not persist to the runtime container. The way that the buildpacks can set environment variables in the runtime container is via the `.profile.d` interface. Before the app boots up, all scripts in the `.profile.d` directory of the droplet will get run. 

For example, if my buildpack wants to set "TEST_VARIABLE" to 1 in the runtime container, the following code in the `bin/compile` script would enable this:

```
mkdir -p .profile.d
echo "export TEST_VARIABLE=1" >> .profile.d/test.sh
chmod +x .profile.d/test.sh
```

You can also find more real-world examples of this in the various Cloud Foundry buildpacks. Searching for ".profile.d" will help.

Cloud Foundry Docs reference: https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#set-env

**Comment by pkumar-appd** [comment]
Thanks @RochesterinNYC for the help.

**Comment by ewmiller** [comment]
Do .profile.d scripts run before the buildpack is installed, or after the buildpack install but before app startup? I'm finding conflicting answers. I'd love a way to run a bash script before the buildpack itself even runs, because I need to configure my environment a specific way in order for `pip install` to succeed.

**Comment by dgodd** [comment]
@ewmiller It sounds like you probably want to use `cf set-env` . 

profile.d scripts run at runtime (not staging) and before the start command

**Comment by ewmiller** [comment]
@dgodd thanks for the response. I actually need to create a file in the system's ~/ directory, not just set environment variables, so I'm not sure if `cf set-env` would do the trick. Though it looks like #86 might be addressing a similar problem, I'm just unclear about the workaround they mentioned.
