### ISSUE TITLE
Copying into the container failed

### ISSUE THREAD

**Issue by crawles** [cloudfoundry/python-buildpack#47]
I am relaying an issue I encountered and am providing the solution I am using.

What version of Cloud Foundry are you using?
API endpoint: https://api.local2.pcfdev.io (API version: 2.54.0)

What version of the buildpack you are using?
 buildpack: https://github.com/cloudfoundry/python-buildpack.git

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing an app 

https://github.com/crawles/text-analytics-service-example/tree/2bdc7a695459dc67877bf8ccd7f38ba238af32b5/flask_deployment

What did you expect to happen?
It to deploy

What was the actual behavior?
It failed due to:

`2016-08-24T10:18:18.08-0400 [API/0]      OUT App instance exited with guid 88003cf8-e493-4ece-a610-f36f3b2a0fce payload: {"instance"=>"7243f261-0f66-4db4-6fc8-eea5bfdc4a67", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"Copying into the container failed", "crash_count"=>4, "crash_timestamp"=>1472048298064998585, "version"=>"ee271b31-6a2b-4b51-ae0c-589d06392855"}`

This error is fixed when I changed the disk and memory from 512MB to 1 GB. The app is one python file and here is the environment.yml. I would desire the error message be more descriptive of why copying into the container failed. I guess there wasn't enough room? Had to figure out from googling and trial and error
 
Please confirm where necessary:
* [ x] I have included a log output 
* [ x] My log includes an error message 
* [ x] I have included steps for reproduction

**Comment by crawles** [comment]
Just saw this https://github.com/cloudfoundry/python-buildpack/issues/33 . Looks to be same issue

**Comment by RochesterinNYC** [comment]
Hi @crawles, yup, I believe that's the same issue. The buildpack isn't responsible for this error message however. I think it's part of Diego.

**Comment by crawles** [comment]
Makes sense about the error message. Given this particular python app isn't particularly large, does it make sense to it to require 1GB of disk space? Is this a requirement of downloading and installing miniconda?

**Comment by RochesterinNYC** [comment]
Yes, I believe conda and its packages are fairly large.

**Comment by jchesterpivotal** [comment]
Do we have a sense of a "normal" Conda staging size? Might be worth adding to the docs.

**Comment by crawles** [comment]
Here is my "normal" disk usage. I'm currently deploying 5 apps using Anaconda - disk usage is reported from Pivotal Apps Manager.

![screen shot 2016-08-25 at 10 16 34 am](https://cloud.githubusercontent.com/assets/5091145/17972557/1fcfaa48-6aad-11e6-86bd-df6aa7c89736.png)

**Comment by jchesterpivotal** [comment]
The tricky part is that staging disk size and runtime disk size are the same. It's common for staging to have much higher requirements than runtime -- we saw this a lot with Rails apps pulling Nokogiri, for example.

**Comment by jchesterpivotal** [comment]
Unfortunately so. During compilation of any C/C++ you'd have the original archives, the source code, the intermediate object code and then the final binaries. Some of these might be cleaned up as it goes, but there'll be points where there's more disk usage than the final output.

**Comment by RochesterinNYC** [comment]
Closing as I don't believe there's any action items here. Please let us know if you feel otherwise or have any suggestions.
