### ISSUE TITLE
Requirements.in is missing in feature

### ISSUE THREAD

**Issue by yogananda-muthaiah** [cloudfoundry/python-buildpack#479]
How about requirements.in instead of requirements.txt ??

Currently this feature is missing during cf push <app name> or manifest

More info you can find it through https://medium.com/@ramalhodevitor/abandon-requirements-txt-for-managing-dependencies-in-python-immediately-50b1c45b824a

**Comment by johnnyr0x** [comment]
Moving to icebox. Have not heard any other feedback from the community on this feature.

**Comment by robdimsdale** [comment]
I'm going to close this issue as there has been no update in over a year.
