### ISSUE TITLE
PIP Uninstall fails during Deployement

### ISSUE THREAD

**Issue by BonsaiDen** [cloudfoundry/python-buildpack#49]
What version of Cloud Foundry are you using?

> CLI: version 6.19.0+b29b4e0-2016-06-08 
> API: version: 2.43.0

What version of the buildpack you are using?

> 1.5.1

If you were attempting to accomplish a task, what was it you were attempting to do?

> Deploy the application.

What did you expect to happen?

> Application should get deployed.

What was the actual behavior?

> Deployment fails due to PIP not being able to uninstall old versions of the applications dependencies. 

Please confirm where necessary:
* [x] I have included a log output: https://gist.github.com/BonsaiDen/f34c4b72b779cd587410c45cf79f0808
* [x] My log includes an error message 
* [ ] I have included steps for reproduction

**Comment by RochesterinNYC** [comment]
Hi @BonsaiDen, thanks for the issue. Does this issue still occur on the latest version of the buildpack (`1.5.9`)? Additionally, can you provide the app this occurs with? Or at least a minimal reproduction app?

**Comment by BonsaiDen** [comment]
Hi @RochesterinNYC,

thanks for your response. I'll contact our customer to upgrade the buildpack version on their CF installation.

A minimal reproduction app would be rather complicated to set up. From what I can tell, it seems that the build artifacts cache got corrupted somehow and now PIP is trying to un-install a number of packages from the cache which are no longer actually present. Which eventually leads to the failure described in this ticket.

Well, at least that's my theory at the moment :)

I've searched through the CF docs a number of times now, but there doesn't seem to be a way to clear the build artitfacts cache via the command line. But maybe I'm missing something?

Anyways, I'll get back to you once our customer has upgraded their Buildpack to the latest version , might take a day or two though.

**Comment by RochesterinNYC** [comment]
@BonsaiDen gotcha, thanks. Please keep us updated.

The only way to delete the staging cache that we're aware of at the moment is to delete your application and push it up again. I'm not sure if there are other ways.

**Comment by BonsaiDen** [comment]
Jo @RochesterinNYC,

our customer did upgrade the Buildpack to the latest version and as it appears this has fixed the issues with PIP uninstall failing.

I also updated our dependencies one more time to ensure that it's not a one time effect and from what I can tell PIP is now working as expected every time. Therefore the issue can be closed.

Thanks for you support!

**Comment by RochesterinNYC** [comment]
Great to hear. Cheers!
