### ISSUE TITLE
Adding odbc driver in python buildpack

### ISSUE THREAD

**Issue by aimengda** [cloudfoundry/python-buildpack#526]
Is there any possibility to add ODBC driver to the build pack because most of the python projects rely on the driver to connect to database.

**Comment by arjun024** [comment]
I believer ODBC driver is already part of the rootfs.
See https://github.com/cloudfoundry/cflinuxfs3/blob/0.301.0/receipt.cflinuxfs3.x86_64

```
‣ docker run --init -it cloudfoundry/cflinuxfs3 sh -c 'odbcinst -j'
unixODBC 2.3.4
```

Are you facing any problems?

**Comment by aimengda** [comment]
I believe unixODBC is a driver manager, but the driver is not there. I can't connect to MSSQL using pyodbc, the error message shows that it's related to the driver(Free TDS or MSSQL ODBC).

发件人：Arjun Sreedharan ***@***.***>
发送日期：2022-05-27 01:57:31
收件人：cloudfoundry/python-buildpack ***@***.***>
抄送人："王梦达" ***@***.***>,Author ***@***.***>
主题：Re: [cloudfoundry/python-buildpack] Adding odbc driver in python buildpack (Issue #526)

I believer ODBC driver is already part of the rootfs.
 See https://github.com/cloudfoundry/cflinuxfs3/blob/0.301.0/receipt.cflinuxfs3.x86_64
‣ docker run --init -it cloudfoundry/cflinuxfs3 sh -c 'odbcinst -j'

unixODBC 2.3.4

Are you facing any problems?

**Comment by aimengda** [comment]
I'm using Django framework and the code is like MS sample code: https://github.com/Azure/azure-sql-database-samples/tree/master/django/django-pyodbc-azure, and the error I got is 
![image](https://user-images.githubusercontent.com/37826258/171406706-28a9c061-f63c-45af-854d-8983cb25ece6.png)

**Comment by arjun024** [comment]
From the given info, it looks like your app has a perquisite on FreeTDS which supplies the ODBC Driver for SQL Server on Linux.
I have a few options that you can try:

* Use the **experimental** [apt-buildpack](https://github.com/cloudfoundry/apt-buildpack) to install the prerequisites. Note that apt-buildpack is a no-guarantees buildpack and works only for installing simple packages.
* Create a custom stack and add your packages. You should be able to fork cflinuxfs3 and make your changes.
* Build the missing dependencies yourself and push them with the app. You’d have to pre-compile all the dependencies you need, add them in the app directory, and use a [`.profile`](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#(optional)-configure-app-initialization) file to set any environment config you would need at launch (e.g. `PATH`, `LD_LIBRARY_PATH`, etc.)

**Comment by aimengda** [comment]
Pushing the driver with app and set it up in a customize start bash file solved my problem, thanks.

From: Arjun Sreedharan ***@***.***>
Date: 2022-06-02 00:27:36
To: cloudfoundry/python-buildpack ***@***.***>
Cc: "王梦达" ***@***.***>,Author ***@***.***>
Subject: Re: [cloudfoundry/python-buildpack] Adding odbc driver in python buildpack (Issue #526)

From the given info, it looks like your app has a perquisite on FreeTDS which supplies the ODBC Driver for SQL Server on Linux.
 I have a few options that you can try:
Use the experimental apt-buildpack to install the prerequisites. Note that apt-buildpack is a no-guarantees buildpack and works only for installing simple packages. Create a custom stack and add your packages. You should be able to fork cflinuxfs3 and make your changes. Build the missing dependencies yourself and push them with the app. You’d have to pre-compile all the dependencies you need, add them in the app directory, and use a .profile file to set any environment config you would need at launch (e.g. PATH, LD_LIBRARY_PATH, etc.)—

**Comment by aimengda** [comment]
Issue resolved, thanks.
