### ISSUE TITLE
Pull request for APT-GET

### ISSUE THREAD

**Issue by gitricko** [cloudfoundry/python-buildpack#55]
What version of Cloud Foundry are you using?
- Current PCF release

What version of the buildpack you are using?
- Current 1.5.11

If you were attempting to accomplish a task, what was it you were attempting to do?
- I am trying to put a functionality where we can do APT-GET install in the python buildpack. Basically, it is the code from [heruko-apt-get buildpack](https://github.com/ddollar/heroku-buildpack-apt/blob/master/README.md). This allows us to install any linux binaries and the binaries and permission are set correct in the /app/ subfolders
- Please check out the behaviour on my [apt-python-buildpack](https://github.com/gitricko/apt-python-buildpack)
- Essentially, if apt.install file are found, the installing of these binaries begins. Similar to conda's environment.yml

**Comment by RochesterinNYC** [comment]
@gitricko your description is phrased like a pull request but this is submitted as an issue. We're a little unclear on exactly what you're requesting or what your issue is. Can you restate or resubmit as a PR or issue as necessary?

**Comment by gitricko** [comment]
Yes, i think this is more a feature or pull request. I will make a pull request when i make a fork first.

**Comment by RochesterinNYC** [comment]
Sure, but could we also discuss what your intended PR will do ?

We're unlikely to add apt-get functionality to the python buildpack at the moment due to future first class multi-buildpack support. With this kind of support, a general apt-get buildpack could handle this apt-get need for all the buildpacks.

**Comment by gitricko** [comment]
That will be great. My PR essentially is to solve this problem which specifically for python PR. You can see the changes from [here](https://github.com/gitricko/apt-python-buildpack/compare/fc189eed3f40ad405b2e96c3622c6681c56ba3cb...2cbe52126c759b5ec2a4472bdfff4346f7a18ade#files_bucket)

I essentially would just change 3 things.

1. Add apt.install bin-steps. This will do apt-get install from apt.install file. It will install the files appropriately in /app directories and resolve path
2. Modify compile to detect whether apt.install file exist in root app. If so, trigger the bin step before conda.
3. upgrade support conda.install to miniconda 4.2.11 instead 4.1.11. Here i patch the bug in miniconda that pyyaml is not install properly. miniconda 4.2.11 supports custom channels now.

Let me know if you think this PR is useful or will ever merge. If it is not going to be approved, then i leave it in [apt-python-buildpack](https://github.com/gitricko/apt-python-buildpack)

**Comment by RochesterinNYC** [comment]
I don't think we would take the changes relating to the apt-get functionality. With first class multi buildpack support in the platform, similar functionality would be implemented in a specific, interpreter-agnostic buildpack that could be used before any of the existing system buildpacks (including python). This way, the functionality/code is not distributed across buildpacks.

For point number 3, thank you for bringing this to our attention. We were unaware that the miniconda version in the python buildpack was not up to date. We've created stories in our backlog to [update it](https://www.pivotaltracker.com/story/show/135443231) and to [ensure we don't overlook future updates](https://www.pivotaltracker.com/story/show/135443165).

Side note: We took a look and your apt-get buildpack is really clever!

**Comment by gitricko** [comment]
I totally agree with the concept of a cloudfoundry multi-buildpack and couple with a apt-get buildpack as it will work also for java, python, nodejs, go... buildpacks.

Let's us know when these 2 buildpack are ready so that we can use it.

For point 3, we need to be careful and not to have an automatic way to update the conda version. It seems 4.2.11 version forgot to include [pyyml](https://github.com/ContinuumIO/anaconda-issues/issues/1205). This cause all conda env to have problems. Maybe an option to configure during deploy time. (maybe)

Glad that you like the [apt-python-buildpack](https://github.com/gitricko/apt-python-buildpack) but i cannot claim credit for it except integration. Most of the code for APT-GET is from [heroku-buildpack-apt](https://github.com/ddollar/heroku-buildpack-apt)
