### ISSUE TITLE
UCS-4 Unicode support

### ISSUE THREAD

**Issue by afritzler** [cloudfoundry/python-buildpack#56]
Would be great if the PR https://github.com/heroku/heroku-buildpack-python/pull/322 would also make it into the cf python buildpack.

**Comment by RochesterinNYC** [comment]
@afritzler does ucs-4 encapsulate all of ucs-2 in a backwards compatible manner? What we're trying to determine is if someone has staged their app using the current python `2.7.12` in the buildpack and they repush it with a python `2.7.12` that was built with `--enable-unicode=ucs4`, their app will still correctly stage/push?

Since we have a different binary building and distribution process as Heroku, if we wanted to implement this support, we could do it with new rebuilt binaries at any time.

**Comment by afritzler** [comment]
@RochesterinNYC I am not sure about the backwards compatibility. Need to check that. In our case we were facing the problem, that if you vendor modules on a vanilla ubuntu/trusty system, those modules are `ucs-4` based. Pushing such an application (using vendoring) results in the issue, that some of the modules will fail.

From my understanding the heroku buildpack will be build using `--enable-unicode=ucs4` flag with the upcoming python version 2.7.13.

**Comment by RochesterinNYC** [comment]
@afritzler your use case makes sense. We'd like to implement this change and have all of the python versions in the buildpack built with ucs4, but want to find out more about the compatibility situation.

**Comment by sclevine** [comment]
Created a story to investigate:
https://www.pivotaltracker.com/story/show/136216257

And prioritized this issue pending the investigation:
https://www.pivotaltracker.com/story/show/135018119

**Comment by afritzler** [comment]
The heroku guys just merged https://github.com/heroku/heroku-buildpack-python/pull/322#event-896991099 and added `python-2.7.13` with `ucs-4` support.

**Comment by afritzler** [comment]
Any updates on this issue? I saw that you bumped the Python version to 2.7.13 in the latest BP release. Is the UCS issue also incorporated?

**Comment by dgodd** [comment]
@afritzler We did not handle UCS-4 as part of the bump to 2.7.13, the links sclevine mentioned above are tracking our work on UCS-4

https://www.pivotaltracker.com/story/show/136216257
https://www.pivotaltracker.com/story/show/135018119

**Comment by sesmith177** [comment]
@afritzler We have prioritized the the stories to do this work in tracker; you can follow the progress using the links posted above by @dgodd

**Comment by afritzler** [comment]
@sesmith177 Thanks a lot for the update!

**Comment by afritzler** [comment]
This issue is tagged as `unscheduled`. Any chance we can push that a bit? The heroku fix for this problem looks pretty straight forward: https://github.com/heroku/heroku-buildpack-python/blob/master/builds/runtimes/python-2.7.13#L13

**Comment by sclevine** [comment]
We finished the investigative story last week and concluded that this is a breaking change for Python 2.7 users who use UCS-2. This includes many Windows users and macOS users who use the system Python 2.7 or Homebrew:
https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L15
https://github.com/Homebrew/legacy-homebrew/pull/32368

Unfortunately, this means that we'll need to give a 30-day notice to the community before we can make a release that includes UCS-4 support. I'll send that notice out soon.

If this is time sensitive for you, you could build and host a UCS-4 Python 2.7 using our binary-builder: https://github.com/cloudfoundry/binary-builder/blob/master/recipe/python.rb#L7

And then fork the buildpack and update the manifest:
https://github.com/cloudfoundry/python-buildpack/blob/master/manifest.yml#L40

Apologies for the low prioritization of this issue.

**Comment by sesmith177** [comment]
Hello @afritzler,

Python buildpack release 1.5.18 contains python 2.7.x binaries with UCS-4 support and will use them by default.

The next buildpack release will remove the python 2.7.x UCS-2 binaries altogether
