### ISSUE TITLE
Broken geo-lib step in buildpack

### ISSUE THREAD

**Issue by Jonty** [cloudfoundry/python-buildpack#62]
The [`geo-libs` step](https://github.com/cloudfoundry/python-buildpack/blob/master/bin/steps/geo-libs) of the buildpack compile is currently broken because it refers to the Heroku binaries URL, and the dependencies are not actually listed in the `manifest.yml`.

The installation appears to succeed because the curl fetching has all errors sent to `/dev/null` and pipefail is not set.

## To replicate
1. Push a test python app
2. `cf set-env APPNAME BUILD_WITH_GEO_LIBRARIES 1`
3. `cf restage APPNAME`
4. `cf ssh APPNAME`
5. `ls app/.heroku/vendor` and observe that it is empty

## In order to fix this
1. The `curl` fetching needs to be refactored to use `download_dependency`
2. The `gdal`, `geos`, and `proj` dependencies need to be built and uploaded to the buildpack dependency bucket
3. `manifest.yml` needs to have the dependencies listed

## Other notes
* The `bin/steps/gdal` step is also broken in the same way, however given `geo-lib` installs `gdal` the best fix may be to remove that step entirely.

**Comment by sclevine** [comment]
Story to fix these steps: https://www.pivotaltracker.com/story/show/138615797

**Comment by sclevine** [comment]
Hi @Jonty,

Unfortunately, GDAL is too large to include in the cached (offline) version of the buildpack, so we won't be able to add support for it. Instead, you could consider [this buildpack](https://github.com/boundlessgeo/osgeolib-buildpack) that provides GDAL and other geospacial libs.

**Comment by Jonty** [comment]
@sclevine Looking at the compiled binary it's ~600k - what is the limit for offline buildpacks?

Also would it be possible to only support something in the online buildpack and not the offline one?

**Comment by sclevine** [comment]
@dgodd found that adding these libraries increased the sized of the cached buildpack by ~100MB. That is large enough that we can't add it to the buildpack without many users demanding it.

We only allow online-only functionality in the cached buildpack when that functionality wouldn't make sense in an offline environment.

We plan to deliver support for multiple buildpacks in CF this year. Support for extension buildpacks will make it easy to include extra libraries like these in your apps.

**Comment by sclevine** [comment]
@Jonty The story [here](https://www.pivotaltracker.com/story/show/138615797) has details about replicating working geo-libs behavior in your app.

**Comment by Jonty** [comment]
To help those in the future who may run across this:

* The python builtpack supports pre-compile and post-compile hooks, so we can utilise these to install the dependencies.
* Place this in `bin/pre_compile` in your application directory: https://gist.github.com/Jonty/7d4857a0f0104fe3fef39bfd2911bb59
* `cf set-env $YOURAPP BUILD_WITH_GEO_LIBRARIES 1`
* `cf push`
