### ISSUE TITLE
Not able to start my python app through buildpack

### ISSUE THREAD

**Issue by SonalGuptaGemini** [cloudfoundry/python-buildpack#68]
Hi everyone!
I am using this python buildpack -python_buildpack-cached-v1.5.5.zip

My current folder structure:
CF_Python
|__requirements.txt
|__runtime.txt
|__test.py

When i try to run :
 cf push CF_Python

I get the foll error msg:
Uploading CF_Python...
Uploading app files from: J:\Desktop\CF_Python
Uploading 401, 3 files
Done uploading
OK

Starting app CF_Python in org *****_****
Creating container
Successfully created container
Downloading app package...
Downloaded app package (509B)
Staging...
-------> Buildpack version 1.5.5
 !     Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
 !     Learn more: https://devcenter.heroku.com/articles/procfile
-----> Installing python-2.7.11

     $ pip install -r requirements.txt
DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
You must give at least one requirement to install (see "pip help install")
No start command detected; command must be provided at runtime
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (28.6M)
Uploaded droplet (28.6M)
Uploading complete

0 of 1 instances running, 1 crashed
FAILED
Start unsuccessful

TIP: use 'cf logs CF_Python --recent' for more information

I am not so good with CF , please can anyone help me with this error.. It is a bit urgent :(

**Comment by SonalGuptaGemini** [comment]
**Can anyone please help on this? 
Thanks** 

Hi everyone!
I am using this python buildpack -python_buildpack-cached-v1.5.5.zip

My current folder structure:
CF_Python
|__requirements.txt
|__runtime.txt
|__test.py

When i try to run :
cf push CF_Python

I get the foll error msg:
Uploading CF_Python...
Uploading app files from: J:\Desktop\CF_Python
Uploading 401, 3 files
Done uploading
OK

Starting app CF_Python in org *_
Creating container
Successfully created container
Downloading app package...
Downloaded app package (509B)
Staging...
-------> Buildpack version 1.5.5
! Warning: Your application is missing a Procfile. This file tells Heroku how to run your application.
! Learn more: https://devcenter.heroku.com/articles/procfile
-----> Installing python-2.7.11

 $ pip install -r requirements.txt
DEPRECATION: --allow-all-external has been deprecated and will be removed in the future. Due to changes in the repository protocol, it no longer has any effect.
You must give at least one requirement to install (see "pip help install")
No start command detected; command must be provided at runtime
Exit status 0
Staging complete
Uploading droplet, build artifacts cache...
Uploading build artifacts cache...
Uploading droplet...
Uploaded build artifacts cache (28.6M)
Uploaded droplet (28.6M)
Uploading complete

0 of 1 instances running, 1 crashed
FAILED
Start unsuccessful

TIP: use 'cf logs CF_Python --recent' for more information

I am not so good with CF , please can anyone help me with this error.. It is a bit urgent :(

**Comment by sclevine** [comment]
Hi @SonalGuptaGemini,

You need to provide a start command for your app, either in a `Procfile` or `manifest.yml` file.
See: http://docs.cloudfoundry.org/buildpacks/python/#start-command

**Comment by SonalGuptaGemini** [comment]
Thanks for your response!

But I am not using a web app. I am building a backend application in Python where I have few Python scripts. The start command which is mentioned in the document says that my application needs to be a web app, which is not the case in my Python application

**Comment by sclevine** [comment]
You must provide a start command for CF to start your app.
You could set a dummy start command and disable health checking:
```
cf push CF_Python -u none -s cat
```
But then nothing will be able to communicate with your backend service, which is probably not what you want.

**Comment by SonalGuptaGemini** [comment]
Mmm.. Yes probably.. But let me try this

**Comment by SonalGuptaGemini** [comment]
Thanks a lot @sclevine !!
This command started my app.. But it will be a great help if you can help me understand this command. Or can provide sme  documentation links?:)

**Comment by sclevine** [comment]
Sorry, my instructions were somewhat misleading. That command didn't really "start your app," it just allocated a container with your app files, with the `cat` process running (which doesn't do anything in this context). 

If you really don't want anything to talk to your app (for instance, because it's a DB worker app), then you could start it like this:
```
cf push CF_Python -u none -c "<YOUR PYTHON START COMMAND HERE>"
```
(Or specify the `web:` directive in the Procfile, which is essentially the same thing as `-c`.)

CF expects that apps will bind to the port specified by the provided env var `$PORT`. If an app doesn't bind to that port, CF will assume something is wrong and destroy the app. The `-u none` option disables this health check, so that any start command (including one that doesn't actually run any of your app code, like `cat`) will suffice.

Here's a reference for the cf CLI: https://docs.cloudfoundry.org/cf-cli/cf-help.html

**Comment by SonalGuptaGemini** [comment]
Thanks @sclevine for the explanation :)

**Comment by calmzhu** [comment]
@sclevine  Same problems on me . But still not work after add a start command, Can you give same tops please, Thanks.

This is my manifest.yml. It's a simple django app
```yaml
applications:
    - name: djangoapp
      instance: 1
      memory: 512M
      buildpack: python_buildpack
      command: "python manager.py runserver 0.0.0.0:8080"
      envs:
          DISABLE_COLLECTSTATIC: 1
```
And erros occured. Seemed start command not worked
```
 No start command specified by buildpack or via Procfile.
```

And After I  close helthcheck with `cf push -u none`.
```
[ERR] python: can't open file 'manager.py': [Errno 2] No such file or directory
```
