### ISSUE TITLE
Staging fails due to out of space for larger python applications

### ISSUE THREAD

**Issue by alexpenev-s** [cloudfoundry/python-buildpack#71]
The staging container in CF is defaulted to 4G. 
Some python applications with large dependencies fail to deploy. 
It would be great if we could optimize the disk usage by the buildpack.

For one such application I see the following disk space used by the buildpack:
339M    /tmp/buildpack
339M    /tmp/buildpacks
808M    /tmp/cache
1.1G    /tmp/app

If we use symlinks between the buildpack dirs & $CACHE_DIR/.cloudfoundry/python and $APP_DIR/.cloudfoundry a lot of the disk space could be saved. 

Here is the disk usage for the same application inside the staging container when symlinks are used:

420K    /tmp/buildpack
339M    /tmp/buildpacks
808M    /tmp/cache
250M    /tmp/app

There is over 1G of disk difference.
The buildpack would also run faster as it isn’t copying large files across.

**Comment by sclevine** [comment]
This seems very reasonable, although I'd like to explore whether it's necessary to have these files in two places at all. I'll prioritize an investigation into merging #72 (or reducing the copying some other way), after you sign the CLA in #72.

**Comment by alexpenev-s** [comment]
CLA done.

**Comment by dturanski** [comment]
Hitting the same issue especially with conda. I'll try it with the `develop` branch and see if this fixes it.

**Comment by sclevine** [comment]
Should be fixed on `develop`. We plan to cut a new release very soon.

**Comment by dturanski** [comment]
Just verified it works for my app.  Thanks!!

**Comment by sclevine** [comment]
Released.
