### ISSUE TITLE
potential security issue

### ISSUE THREAD

**Issue by pourquoi42** [cloudfoundry/python-buildpack#73]
Hi,

in the context of a security review of a cf app based on this buildpack, I found something wihich is in my opinion a potential general vulnerability of services build with this buildpack. Whom could I contact with this?

**Comment by sclevine** [comment]
Hi @pourquoi42,

Please disclose this potential vulnerability to **security@cloudfoundry.org** at your soonest convenience. More information, including a GPG key to sign and/or encrypt your disclosure with (if desired), is available at: https://cloudfoundry.org/security/

Thanks,
Stephen

**Comment by sclevine** [comment]
@pourquoi42, we haven't received a report from you yet -- do you still believe that you've identified a vulnerability?
