### ISSUE TITLE
Use switchblade for integration testing

### ISSUE THREAD

**Issue by ryanmoran** [cloudfoundry/python-buildpack#730]
"Switchblade is an integration testing framework for Cloud Foundry v2b buildpacks. It enables test authors to write tests once, and then run them either against a real Cloud Foundry, or their local Docker daemon."

Using [switchblade](https://github.com/ryanmoran/switchblade) in our integration testing should greatly improve the ability to rapidly iterate during buildpack development.

There is already an existing attempt to do this work on this branch: https://github.com/cloudfoundry/python-buildpack/tree/use-switchblade

**Comment by ryanmoran** [comment]
@brayanhenao since you had started this work, is there any other context needed here or understanding of the state this WIP branch is in?

**Comment by brayanhenao** [comment]
@ryanmoran That branch was an attempt (which I abandoned due to lack of time) to use the same structure you had used for go/node in switchblade. There is not much progress, so the person who will be in charge of doing this migration either can re-use the branch or start from scratch.

**Comment by robdimsdale** [comment]
Closed via #746
