### ISSUE TITLE
Vendor of OS Specific Libraries

### ISSUE THREAD

**Issue by rjain-pivotal** [cloudfoundry/python-buildpack#75]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

   "min_cli_version": "6.22.0",
   "min_recommended_cli_version": "latest",
   "api_version": "2.84.0",

cf version 6.26.0+9c9a261fd.2017-04-06

What version of the buildpack you are using?
python_buildpack-cached-v1.5.18.zip
and latest buildpack(  buildpack: https://github.com/cloudfoundry/python-buildpack.git
) , using runtime.txt ==> python-3.5.3

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push with vendored libraries of urwid and aiohttp

What did you expect to happen?
cf push is successful in creating the container

What was the actual behavior?
not able to vendor the libraries of urwid and aiohttp

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

This is a documentation issue: 

Here is what you can add in the documentation. The vendored libraries are OS Specific. In order to vendor the correct libraries (packages) you can create a runtime.txt with the appropriate version of the python and cleanup you local vendor directory before doing a cf push

Sample cf app which can be used to reproduce this issue, if you don't have the runtime.txt and have vendored packages. 
https://github.com/rjain-pivotal/python-cf-app

**Comment by sclevine** [comment]
Thanks for the report @rjain-pivotal. We'll update the docs.

**Comment by sclevine** [comment]
Docs updated.
