### ISSUE TITLE
More than two returns on runtime.txt breaks buildpack 

### ISSUE THREAD

**Issue by hbastosc** [cloudfoundry/python-buildpack#76]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

cf version
cf version 6.26.0+9c9a261.2017-04-06
"api_version": "2.81.0",

What version of the buildpack you are using?
1.5.18

If you were attempting to accomplish a task, what was it you were attempting to do?
Push a regular Flask application

What did you expect to happen?
Builpack to create the app succesfully.

The reason for this to fail was because we found out that gvim on windows was adding an extra return to the file. 

What was the actual behavior?
Staging...
-------> Buildpack version 1.5.18
-----> Installing python-3.5.2
/usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://lang-python.s3.amazonaws.com//runtimes/python-3.5.2
.tar.gz (URI::InvalidURIError)
        from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
        from /usr/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
        from /usr/lib/ruby/2.3.0/uri/common.rb:714:in `URI'
        from /tmp/buildpack/compile-extensions/lib/uri_translator.rb:30:in `filter_uri'
        from /tmp/buildpack/compile-extensions/lib/uri_translator.rb:15:in `translate'
        from /tmp/buildpack/compile-extensions/bin/download_dependency:15:in `<main>'
DEPENDENCY MISSING IN MANIFEST:
Unfortunately, we are either unable to resolve the dependency into
a binary and version number or the requested version or version range is not supported.
Please replace the URL with a valid link or the requested version/range
with a supported version or version range.
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223
Destroying container
Successfully destroyed container

FAILED
Error restarting application: BuildpackCompileFailed

**Comment by sclevine** [comment]
Fixed on develop: ebc533c0d534cac1c217c2c755291bbbb1b73487
This fix will be available in the next release.
