### ISSUE TITLE
Conda upgrade & custom solver

### ISSUE THREAD

**Issue by sumanth-manchala** [cloudfoundry/python-buildpack#761]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 7.0.2

What version of the buildpack you are using?
1.8.7

If you were attempting to accomplish a task, what was it you were attempting to do?
I am attempting to use conda version > 22.9.0 and set the solver to be libmamba.
Please refer: https://conda.github.io/conda-libmamba-solver/getting-started/

What did you expect to happen?

What was the actual behavior?
Currently conda/minconda has not been upgraded from almost an year and there is no way to set an upgraded version/customize create and install commands

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sumanth-manchala** [comment]
Team, Any further updates on this issue. We are seeing a memory spike especially during conda environment solving and some of enhacement to conda/solver changes might help us decreasing our memory

**Comment by arjun024** [comment]
@sumanth-manchala Sorry, this could be an issue with our tool watching the upstream dependency. Taking a look

**Comment by sumanth-manchala** [comment]
Thanks a lot @arjun024, When can we expect a build pack release reflecting these changes?

**Comment by arjun024** [comment]
@sumanth-manchala The pipeline had a little hiccup which I have fixed now. It's PR-ed in the change at https://github.com/cloudfoundry/python-buildpack/pull/802, but miniconda version upgrades can be a little tricky if they don't pass the integration tests.
Buildpacks are released on a monthly cadence (unless there's a pressing issue like a critical CVE fix) - so you can expect the newer version to be shipped early next month. You can also consume the "develop" branch once the PR is merged if you're fine with consuming a buildpack that hasn't passed the tests.

The upstream watcher tool immediately picks up a version on release and PRs into the buildpack but in this case, miniconda changed their versioning scheme and we missed out on updating our infrastructure.
