### ISSUE TITLE
Integration Test are failing 

### ISSUE THREAD

**Issue by liornabat-sealights** [cloudfoundry/python-buildpack#788]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "Small Footprint VMware Tanzu Application Service",
   "build": "4.0.3-build.1",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "https://docs.pivotal.io/pivotalcf/4-0/pcf-release-notes/runtime-rn.html",
   "authorization_endpoint": "https://login.sys.spanishskyblue.cf-app.com",
   "token_endpoint": "https://uaa.sys.spanishskyblue.cf-app.com",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "app_ssh_endpoint": "ssh.sys.spanishskyblue.cf-app.com:2222",
   "app_ssh_host_key_fingerprint": "04:b6:82:d3:f4:3b:16:b4:71:14:46:b2:2b:40:8c:cd",
   "app_ssh_oauth_client": "ssh-proxy",
   "doppler_logging_endpoint": "wss://doppler.sys.spanishskyblue.cf-app.com:443",
   "api_version": "2.203.0",
   "osbapi_version": "2.15",
   "routing_endpoint": "https://api.sys.spanishskyblue.cf-app.com/routing",
   "user": "33cd6b4b-2d5f-49be-86e1-8134f381e619"
}

cf version 6.49.0+d0dfa93bb.2020-01-07

What version of the buildpack you are using?
latest

If you were attempting to accomplish a task, what was it you were attempting to do?
running integration test scripts.
i have done:
1.  cf login -a https://api.sys.spanishskyblue.cf-app.com -u admin -p  // the password from the admin creds tab
2. run ./scripts/integration.sh  

What did you expect to happen?
passed test

What was the actual behavior?
    init_test.go:81: 
        Unexpected error:
            <*fmt.wrapError | 0x140004301e0>: 
            failed to map-route: exit status 1

Log:
attached file

Please confirm where necessary:
* [ x] I have included a log output
* [ x] My log includes an error message
* [ x
[integration-tests.log](https://github.com/cloudfoundry/python-buildpack/files/11879948/integration-tests.log)
] I have included steps for reproduction

**Comment by robdimsdale** [comment]
Assuming you on running on the `main` branch, this looks like a failure to push the proxy app ([init_test.go:81](https://github.com/cloudfoundry/python-buildpack/blob/60b0fa9230fb779cda0105466678259ce1a09586/src/python/integration/init_test.go#L79-L81)):

```
        proxyDeployment, _, err := proxyDeploymentProcess.
                Execute(proxyName, filepath.Join(fixtures, "util", "proxy"))
        Expect(err).NotTo(HaveOccurred())
```

This seems like an issue with the cloud foundry instance, not the integration tests. Are you able to reproduce this? I'd expect it to be a transient error with the CF installation.

**Comment by liornabat-sealights** [comment]
Yes, i can reproduce  it all the time.
this is using our test instance and i tested it with difference instances.
Since this is a testing instance, i can provide the proper creds to show and reproduce if needed.
Will be appreciate any guidance.

**Comment by robdimsdale** [comment]
Your logs show:

```
            Server error, status code: 404, error code: 210009, message: The router group could not be found: 
```

This sounds like an issue with the Cloud Foundry installation, not the python buildpack. Have you successfully pushed any other applications? Can you push the proxy app by itself?

**Comment by liornabat-sealights** [comment]
Yes, my application is pushed without any problem.
to who i should check this ?

**Comment by robdimsdale** [comment]
Can you point me to the line of code in switchblade that you think is failing?

It's hard for us to debug this as we can't reproduce it in our environments, so it has to be something different about the way your CF is set up. I recognize that you may not be responsible for setting up the CF environment so you may not know what is different, or even be able to change the setup, but it's also not yet clear what change we could make in the python buildpack or switchblade test library to resolve this.

**Comment by liornabat-sealights** [comment]
Just to clear, since we cannot run the integration tests, we cannot pass the PR for our hook to be integrated
