### ISSUE TITLE
Tests failing behind a http proxy (CF internal)

### ISSUE THREAD

**Issue by rakrup** [cloudfoundry/python-buildpack#85]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

v2.65.0

What version of the buildpack you are using?

v1.5.24

If you were attempting to accomplish a task, what was it you were attempting to do?

Trying to run the machete tests with a offline buildpack to make sure all the tests are passing.
The setup is using a offline buildpack and is behind a http-proxy.

What did you expect to happen?

Expect all the integration tests to pass.

What was the actual behavior?

If I try to run the tests without sourcing the proxy in the env. Some of the tests fail because pip fails to fetch the app dependencies from the internet (pip can't get to the proxy). 

If I try to run the tests after sourcing the proxy (and setting the correct no_proxy settings) - some of the test cases which depend of machete's browser emulator fail because it sends all the app  GET requests to the proxy as well and proxy fails to resolve the DNS because CF is running internally.

Please confirm where necessary:
* [ ] I have included steps for reproduction

**Comment by dgodd** [comment]
@rakrup Can I confirm where the proxy is required. I think you are running the buildpack integration tests on a machine which needs to use a http proxy to access the CF cluster, and it is that hop which is failing? Or is http proxy failing somewhere else?

See also: https://github.com/cloudfoundry/python-buildpack/issues/85

**Comment by rakrup** [comment]
@dgodd . Thanks for looking at this.

The machine from where I am running the integration tests is in the same network as the CF (internal instance) so can reach it without using a HTTP proxy. But to have internet connectivity we need to go via a proxy. So I have `http_proxy`,`http_proxy` and `no_proxy` exported. `no_proxy` contains the domain for the CF instance. 

The problem I am facing that my cli works good (coz of no_proxy allows reachability to internal CF & its apps) but when the machete runs and try to reach out to them after spawning them on CF the call goes to the proxy and it gets a DNS resolution error. Problem being that `Browser` implementation inside the `machete` framework is unable to read the 'no_poxy' from the environment. This is is my assumed root cause of the issue. 

Please advice if you feel something else is a problem. 

One more question - the documents on machete or the build pack docs do not focus much on the test requirements from the setup perspective. Say, if my CloudFoundry doesn't have connectivity to the internet. Will machete be able to run all its tests or do some of the tests assume that the internet connectivity is present ?

Ideally I would have assumed that if I was using a --cached parameter - machete would assume also assume that my CF would not have internet connectivity. I could be wrong here and probably I am as I see the tests trying to fetch it from the cloud foundry and failing. A little more clarity on this would help   in a big way.

Thanks,
Rahul.

**Comment by dgodd** [comment]
Re: `--cached` parameter, it will need to download the files in the manifest on your machine before running the tests. After running it once (and thus having the manifest dependencies cached) you should be able to run without internet access

Re:  `NO_PROXY` are you using FQDN or IP addresses or something else? (to make sure I cover your use case). Could you please provide an example?

**Comment by sclevine** [comment]
Let's move this discussion to https://github.com/cloudfoundry/machete/issues/31.
