### ISSUE TITLE
setuptools 32.1.0

### ISSUE THREAD

**Issue by prabu-rethinakumar** [cloudfoundry/python-buildpack#87]
[requirements.txt](https://github.com/cloudfoundry/python-buildpack/files/1416211/requirements.txt)
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
{
   "name": "",
   "build": "",
   "support": "https://support.pivotal.io",
   "version": 0,
   "description": "",
   "min_cli_version": "6.23.0",
   "min_recommended_cli_version": "6.23.0",
   "api_version": "2.82.0",
   "app_ssh_oauth_client": "ssh-proxy",
   "user": "a33ea004-676b-4f87-a1c1-cc435fc87468"
}
cf version 6.25.0+787326d.2017-02-28

What version of the buildpack you are using?
1.6.1

If you were attempting to accomplish a task, what was it you were attempting to do?
Pushing a python/flask application with requirements.txt and manifest.yml to CF

What did you expect to happen?
Successful push to CF

What was the actual behavior?
Getting the below error
[ERR] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/contents232737424/deps/0/python/lib/python3.6/site-packages/setuptools-32.1.0-py3.6.egg'

Please confirm where necessary:
* [x ] I have included a log output
* [x ] My log includes an error message
* [x ] I have included steps for reproduction
[CF_Log.txt](https://github.com/cloudfoundry/python-buildpack/files/1416210/CF_Log.txt)
[manifest.txt](https://github.com/cloudfoundry/python-buildpack/files/1416228/manifest.txt)

**Comment by dgodd** [comment]
Hi @prabu-rethinakumar Could you please provide an app which exhibits this behavior? It will speed up our debugging

**Comment by prabu-rethinakumar** [comment]
Sorry for the delayed response. I will attach the app shortly

**Comment by prabu-rethinakumar** [comment]
Please use this app for testing 
https://github.com/prabu-rethinakumar/CloudfoundryFlask.git

**Comment by prabu-rethinakumar** [comment]
Hi,
I have a work-around though
Adding this line(below)to the end of requirements.txt avoids the failure. This seems to be an issue where setuptools 36.6.0 gets installed while building other dependencies and finally its checking if 32.1.0 exists and fails.
> _setuptools==32.1.0_

**Comment by sclevine** [comment]
@dgodd do we need to account for this scenario, where setuptools is upgrading during staging?

**Comment by sclevine** [comment]
@dgodd @idoru Hearing more complaints about this one -- prioritizing for next week.

**Comment by dgodd** [comment]
@prabu-rethinakumar I just used your app and pushed to CF using python buildpack v1.6.2, and for me this app worked (log attached)
[ABCD.log](https://github.com/cloudfoundry/python-buildpack/files/1517891/ABCD.log)

I then tried using 1.6.1 as you stated you had used that and I saw your error. Does this mean that 1.6.2 has fixed your problem?

**Comment by sclevine** [comment]
Fixed in the latest release.
