### ISSUE TITLE
Please fix the README.md

### ISSUE THREAD

**Issue by tjhgit** [cloudfoundry/python-buildpack#92]
(cd src/staticfile/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)

should be 
(cd src/python/vendor/github.com/cloudfoundry/libbuildpack/packager/buildpack-packager && go install)

**Comment by sclevine** [comment]
Fixed in: 5a71783945be135a7807154b3f4cd658bc0c224d
