### ISSUE TITLE
setuptools installation with certain packages seems to be failing due to known issue.

### ISSUE THREAD

**Issue by AndrewGotz** [cloudfoundry/python-buildpack#956]
Error I am seeing installing certain packages with the python buildpack version of **python v1.8.25**

`AttributeError: module 'setuptools.dist' has no attribute 'check_test_suite'`

https://github.com/pypa/setuptools/issues/4519 Looking here it seems to be a known issue with certain versions of "setuptools" where 72.0 packages seem to have a bug associated with building where it fails for certain packages that use it. I was wondering, is there a way to workaround this issue with the buildpack? Such as setting a different version of the setuptools package?

**Comment by AndrewGotz** [comment]
https://github.com/cloudfoundry/python-buildpack/pull/954 seems like we have a pull request to address this issue, any ETA on when this will get released/merged?

**Comment by arjun024** [comment]
See https://github.com/cloudfoundry/python-buildpack/pull/958
