### ISSUE TITLE
How do you access the Python interpreter used to run your app?

### ISSUE THREAD

**Issue by knowsuchagency** [cloudfoundry/python-buildpack#98]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

    cf curl /v2/info ;; cf version   4.4m  Fri Feb 16 00:16:33 2018
    {
    "name": "",
    "build": "",
    "support": "https://support.run.pivotal.io",
    "version": 0,
    "description": "Cloud Foundry sponsored by Pivotal",
    "authorization_endpoint": "https://login.run.pivotal.io",
    "token_endpoint": "https://uaa.run.pivotal.io",
    "min_cli_version": "6.22.0",
    "min_recommended_cli_version": "latest",
    "api_version": "2.103.0",
    "app_ssh_endpoint": "ssh.run.pivotal.io:2222",
    "app_ssh_oauth_client": "ssh-proxy",
    "doppler_logging_endpoint": "wss://doppler.run.pivotal.io:443",
    "routing_endpoint": "https://api.run.pivotal.io/routing",
    }
    cf version 6.34.1+bbdf81482.2018-01-17

What version of the buildpack you are using?

    v1.6.9

## If you were attempting to accomplish a task, what was it you were attempting to do?

**I'm trying to access the python interpreter used to run
my web application upon ssh-ing into the machine.**

My manifest.yml has the following command

    command: python -m myapp.cli runserver --host 0.0.0.0 --port $PORT

which correctly uses python `3.6.4` as configured in runtime.txt

However, when I SSH into the machine, the default python interpreter is thus

    vcap@machine:~$ which python && python --version
    /usr/bin/python
    Python 2.7.6

additionally

    vcap@machine:~$ which python3 && python3 --version
    /usr/bin/python3
    Python 3.4.3

I found another python interpreter, but I get the following error when I run it

    vcap@machine:~$ cd ~/deps/0/python/bin
    vcap@machine:~/deps/0/python/bin$ ./python
    ./python: error while loading shared libraries: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

**Comment by dgodd** [comment]
At runtime the correct python version should be used. The difference when you ssh in is that the profile.d scripts which setup PATH etc... are not automatically run (again, for the app runtime they are). To obtain the same environment as runtime, please run `/tmp/lifecycle/shell` when you first SSH in.

If your version of cf does not have /tmp/lifecycle/shell ; you can instead run `/tmp/lifecycle/launcher $PWD/app bash ''`

After running the above, you should be in the app directory and you should notice that `$PATH` has changed. When you run `which python && python --version` you should see the expected version

**Comment by knowsuchagency** [comment]
Thanks, that worked!
