### ISSUE TITLE
How to force the running of setup.py during build process?

### ISSUE THREAD

**Issue by knowsuchagency** [cloudfoundry/python-buildpack#99]
Whether or not I have a requirements.txt, Pipfile, or otherwise, I would like to have setup.py execute during the build process. Is there a way to make that happen?

**Comment by dgodd** [comment]
@knowsuchagency I'm asking this as someone who develops in other languages more than python, but why would you want both? Are you able to provide a sample which uses both in a sensible way, then we can consider using it as a fixture for our tests

**Comment by sclevine** [comment]
The buildpack supports running a `/bin/pre_compile` hook in the app directory before staging occurs.

**Comment by sclevine** [comment]
Closing as answered.
